/********************************************************************
 * Copyright (C) 2022 Texas Instruments Incorporated.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *  Name        : cslr_plldig_ctrl.h
*/
#ifndef CSLR_PLLDIG_CTRL_H_
#define CSLR_PLLDIG_CTRL_H_

#ifdef __cplusplus
extern "C"
{
#endif
#include <drivers/hw_include/cslr.h>
#include <stdint.h>

/**************************************************************************
* Hardware Region  :
**************************************************************************/


/**************************************************************************
* Register Overlay Structure
**************************************************************************/

typedef struct {
    volatile uint32_t PID;
    volatile uint32_t PLLDIG_EN;
    volatile uint32_t PLLDIG_MDIV_NDIV;
    volatile uint32_t PLLDIG_CTRL;
    volatile uint32_t PLLDIG_MODE_EN;
    volatile uint32_t PLLDIG_APLL_SW_DIS_DELAY1;
    volatile uint32_t PLLDIG_APLL_SW_DIS_DELAY2;
    volatile uint32_t PLLDIG_OVERRIDE;
    volatile uint32_t PLLDIG_STATUS;
    volatile uint32_t FAST_CLK_MUX_POSTDIV;
    volatile uint32_t FAST_CLK_STATUS;
    volatile uint8_t  Resv_4104[4060];
    volatile uint32_t LOCK0_KICK0;
    volatile uint32_t LOCK0_KICK1;
    volatile uint32_t INTR_RAW_STATUS;
    volatile uint32_t INTR_ENABLED_STATUS_CLEAR;
    volatile uint32_t INTR_ENABLE;
    volatile uint32_t INTR_ENABLE_CLEAR;
    volatile uint32_t EOI;
    volatile uint32_t FAULT_ADDRESS;
    volatile uint32_t FAULT_TYPE_STATUS;
    volatile uint32_t FAULT_ATTR_STATUS;
    volatile uint32_t FAULT_CLEAR;
} CSL_plldig_ctrlRegs;


/**************************************************************************
* Register Macros
**************************************************************************/

#define CSL_PLLDIG_CTRL_PID                                                    (0x00000000U)
#define CSL_PLLDIG_CTRL_PLLDIG_EN                                              (0x00000004U)
#define CSL_PLLDIG_CTRL_PLLDIG_MDIV_NDIV                                       (0x00000008U)
#define CSL_PLLDIG_CTRL_PLLDIG_CTRL                                            (0x0000000CU)
#define CSL_PLLDIG_CTRL_PLLDIG_MODE_EN                                         (0x00000010U)
#define CSL_PLLDIG_CTRL_PLLDIG_APLL_SW_DIS_DELAY1                              (0x00000014U)
#define CSL_PLLDIG_CTRL_PLLDIG_APLL_SW_DIS_DELAY2                              (0x00000018U)
#define CSL_PLLDIG_CTRL_PLLDIG_OVERRIDE                                        (0x0000001CU)
#define CSL_PLLDIG_CTRL_PLLDIG_STATUS                                          (0x00000020U)
#define CSL_PLLDIG_CTRL_FAST_CLK_MUX_POSTDIV                                   (0x00000024U)
#define CSL_PLLDIG_CTRL_FAST_CLK_STATUS                                        (0x00000028U)
#define CSL_PLLDIG_CTRL_LOCK0_KICK0                                            (0x00001008U)
#define CSL_PLLDIG_CTRL_LOCK0_KICK1                                            (0x0000100CU)
#define CSL_PLLDIG_CTRL_INTR_RAW_STATUS                                        (0x00001010U)
#define CSL_PLLDIG_CTRL_INTR_ENABLED_STATUS_CLEAR                              (0x00001014U)
#define CSL_PLLDIG_CTRL_INTR_ENABLE                                            (0x00001018U)
#define CSL_PLLDIG_CTRL_INTR_ENABLE_CLEAR                                      (0x0000101CU)
#define CSL_PLLDIG_CTRL_EOI                                                    (0x00001020U)
#define CSL_PLLDIG_CTRL_FAULT_ADDRESS                                          (0x00001024U)
#define CSL_PLLDIG_CTRL_FAULT_TYPE_STATUS                                      (0x00001028U)
#define CSL_PLLDIG_CTRL_FAULT_ATTR_STATUS                                      (0x0000102CU)
#define CSL_PLLDIG_CTRL_FAULT_CLEAR                                            (0x00001030U)

/**************************************************************************
* Field Definition Macros
**************************************************************************/


/* PID */

#define CSL_PLLDIG_CTRL_PID_PID_MINOR_MASK                                     (0x0000003FU)
#define CSL_PLLDIG_CTRL_PID_PID_MINOR_SHIFT                                    (0x00000000U)
#define CSL_PLLDIG_CTRL_PID_PID_MINOR_RESETVAL                                 (0x00000014U)
#define CSL_PLLDIG_CTRL_PID_PID_MINOR_MAX                                      (0x0000003FU)

#define CSL_PLLDIG_CTRL_PID_PID_CUSTOM_MASK                                    (0x000000C0U)
#define CSL_PLLDIG_CTRL_PID_PID_CUSTOM_SHIFT                                   (0x00000006U)
#define CSL_PLLDIG_CTRL_PID_PID_CUSTOM_RESETVAL                                (0x00000000U)
#define CSL_PLLDIG_CTRL_PID_PID_CUSTOM_MAX                                     (0x00000003U)

#define CSL_PLLDIG_CTRL_PID_PID_MAJOR_MASK                                     (0x00000700U)
#define CSL_PLLDIG_CTRL_PID_PID_MAJOR_SHIFT                                    (0x00000008U)
#define CSL_PLLDIG_CTRL_PID_PID_MAJOR_RESETVAL                                 (0x00000002U)
#define CSL_PLLDIG_CTRL_PID_PID_MAJOR_MAX                                      (0x00000007U)

#define CSL_PLLDIG_CTRL_PID_PID_MISC_MASK                                      (0x0000F800U)
#define CSL_PLLDIG_CTRL_PID_PID_MISC_SHIFT                                     (0x0000000BU)
#define CSL_PLLDIG_CTRL_PID_PID_MISC_RESETVAL                                  (0x00000000U)
#define CSL_PLLDIG_CTRL_PID_PID_MISC_MAX                                       (0x0000001FU)

#define CSL_PLLDIG_CTRL_PID_PID_MSB16_MASK                                     (0xFFFF0000U)
#define CSL_PLLDIG_CTRL_PID_PID_MSB16_SHIFT                                    (0x00000010U)
#define CSL_PLLDIG_CTRL_PID_PID_MSB16_RESETVAL                                 (0x00006180U)
#define CSL_PLLDIG_CTRL_PID_PID_MSB16_MAX                                      (0x0000FFFFU)

#define CSL_PLLDIG_CTRL_PID_RESETVAL                                           (0x61800214U)

/* PLLDIG_EN */

#define CSL_PLLDIG_CTRL_PLLDIG_EN_PLLDIG_EN_CFG_PLLDIG_EN_MASK                 (0x00000007U)
#define CSL_PLLDIG_CTRL_PLLDIG_EN_PLLDIG_EN_CFG_PLLDIG_EN_SHIFT                (0x00000000U)
#define CSL_PLLDIG_CTRL_PLLDIG_EN_PLLDIG_EN_CFG_PLLDIG_EN_RESETVAL             (0x00000000U)
#define CSL_PLLDIG_CTRL_PLLDIG_EN_PLLDIG_EN_CFG_PLLDIG_EN_MAX                  (0x00000007U)

#define CSL_PLLDIG_CTRL_PLLDIG_EN_PLLDIG_EN_CFG_PLL_AUTO_SWITCH_ENABLE_MASK    (0x00000700U)
#define CSL_PLLDIG_CTRL_PLLDIG_EN_PLLDIG_EN_CFG_PLL_AUTO_SWITCH_ENABLE_SHIFT   (0x00000008U)
#define CSL_PLLDIG_CTRL_PLLDIG_EN_PLLDIG_EN_CFG_PLL_AUTO_SWITCH_ENABLE_RESETVAL (0x00000000U)
#define CSL_PLLDIG_CTRL_PLLDIG_EN_PLLDIG_EN_CFG_PLL_AUTO_SWITCH_ENABLE_MAX     (0x00000007U)

#define CSL_PLLDIG_CTRL_PLLDIG_EN_PLLDIG_EN_CFG_PLLDIG_LOCKMON_ENABLE_MASK     (0x00070000U)
#define CSL_PLLDIG_CTRL_PLLDIG_EN_PLLDIG_EN_CFG_PLLDIG_LOCKMON_ENABLE_SHIFT    (0x00000010U)
#define CSL_PLLDIG_CTRL_PLLDIG_EN_PLLDIG_EN_CFG_PLLDIG_LOCKMON_ENABLE_RESETVAL (0x00000000U)
#define CSL_PLLDIG_CTRL_PLLDIG_EN_PLLDIG_EN_CFG_PLLDIG_LOCKMON_ENABLE_MAX      (0x00000007U)

#define CSL_PLLDIG_CTRL_PLLDIG_EN_RESETVAL                                     (0x00000000U)

/* PLLDIG_MDIV_NDIV */

#define CSL_PLLDIG_CTRL_PLLDIG_MDIV_NDIV_PLLDIG_MDIV_NDIV_CFG_PLLDIG_MDIV_MASK (0x000001FFU)
#define CSL_PLLDIG_CTRL_PLLDIG_MDIV_NDIV_PLLDIG_MDIV_NDIV_CFG_PLLDIG_MDIV_SHIFT (0x00000000U)
#define CSL_PLLDIG_CTRL_PLLDIG_MDIV_NDIV_PLLDIG_MDIV_NDIV_CFG_PLLDIG_MDIV_RESETVAL (0x00000000U)
#define CSL_PLLDIG_CTRL_PLLDIG_MDIV_NDIV_PLLDIG_MDIV_NDIV_CFG_PLLDIG_MDIV_MAX  (0x000001FFU)

#define CSL_PLLDIG_CTRL_PLLDIG_MDIV_NDIV_PLLDIG_MDIV_NDIV_CFG_PLLDIG_NDIV_MASK (0x007F0000U)
#define CSL_PLLDIG_CTRL_PLLDIG_MDIV_NDIV_PLLDIG_MDIV_NDIV_CFG_PLLDIG_NDIV_SHIFT (0x00000010U)
#define CSL_PLLDIG_CTRL_PLLDIG_MDIV_NDIV_PLLDIG_MDIV_NDIV_CFG_PLLDIG_NDIV_RESETVAL (0x00000000U)
#define CSL_PLLDIG_CTRL_PLLDIG_MDIV_NDIV_PLLDIG_MDIV_NDIV_CFG_PLLDIG_NDIV_MAX  (0x0000007FU)

#define CSL_PLLDIG_CTRL_PLLDIG_MDIV_NDIV_RESETVAL                              (0x00000000U)

/* PLLDIG_CTRL */

#define CSL_PLLDIG_CTRL_PLLDIG_CTRL_PLLDIG_CTRL_CFG_PLLDIG_CTRL_MASK           (0xFFFFFFFFU)
#define CSL_PLLDIG_CTRL_PLLDIG_CTRL_PLLDIG_CTRL_CFG_PLLDIG_CTRL_SHIFT          (0x00000000U)
#define CSL_PLLDIG_CTRL_PLLDIG_CTRL_PLLDIG_CTRL_CFG_PLLDIG_CTRL_RESETVAL       (0x00000000U)
#define CSL_PLLDIG_CTRL_PLLDIG_CTRL_PLLDIG_CTRL_CFG_PLLDIG_CTRL_MAX            (0xFFFFFFFFU)

#define CSL_PLLDIG_CTRL_PLLDIG_CTRL_RESETVAL                                   (0x00000000U)

/* PLLDIG_MODE_EN */

#define CSL_PLLDIG_CTRL_PLLDIG_MODE_EN_PLLDIG_MODE_EN_CFG_PLLDIG_HIGHFREQ_MODE_EN_MASK (0x00000001U)
#define CSL_PLLDIG_CTRL_PLLDIG_MODE_EN_PLLDIG_MODE_EN_CFG_PLLDIG_HIGHFREQ_MODE_EN_SHIFT (0x00000000U)
#define CSL_PLLDIG_CTRL_PLLDIG_MODE_EN_PLLDIG_MODE_EN_CFG_PLLDIG_HIGHFREQ_MODE_EN_RESETVAL (0x00000001U)
#define CSL_PLLDIG_CTRL_PLLDIG_MODE_EN_PLLDIG_MODE_EN_CFG_PLLDIG_HIGHFREQ_MODE_EN_MAX (0x00000001U)

#define CSL_PLLDIG_CTRL_PLLDIG_MODE_EN_PLLDIG_MODE_EN_CFG_PLLDIG_LOWFREQ_MODE_EN_MASK (0x00010000U)
#define CSL_PLLDIG_CTRL_PLLDIG_MODE_EN_PLLDIG_MODE_EN_CFG_PLLDIG_LOWFREQ_MODE_EN_SHIFT (0x00000010U)
#define CSL_PLLDIG_CTRL_PLLDIG_MODE_EN_PLLDIG_MODE_EN_CFG_PLLDIG_LOWFREQ_MODE_EN_RESETVAL (0x00000001U)
#define CSL_PLLDIG_CTRL_PLLDIG_MODE_EN_PLLDIG_MODE_EN_CFG_PLLDIG_LOWFREQ_MODE_EN_MAX (0x00000001U)

#define CSL_PLLDIG_CTRL_PLLDIG_MODE_EN_RESETVAL                                (0x00010001U)

/* PLLDIG_APLL_SW_DIS_DELAY1 */

#define CSL_PLLDIG_CTRL_PLLDIG_APLL_SW_DIS_DELAY1_PLLDIG_APLL_SW_DIS_DELAY1_CFG_APLL_AUTO_SWITCH_DELAY_MASK (0x0000FFFFU)
#define CSL_PLLDIG_CTRL_PLLDIG_APLL_SW_DIS_DELAY1_PLLDIG_APLL_SW_DIS_DELAY1_CFG_APLL_AUTO_SWITCH_DELAY_SHIFT (0x00000000U)
#define CSL_PLLDIG_CTRL_PLLDIG_APLL_SW_DIS_DELAY1_PLLDIG_APLL_SW_DIS_DELAY1_CFG_APLL_AUTO_SWITCH_DELAY_RESETVAL (0x00000FA0U)
#define CSL_PLLDIG_CTRL_PLLDIG_APLL_SW_DIS_DELAY1_PLLDIG_APLL_SW_DIS_DELAY1_CFG_APLL_AUTO_SWITCH_DELAY_MAX (0x0000FFFFU)

#define CSL_PLLDIG_CTRL_PLLDIG_APLL_SW_DIS_DELAY1_PLLDIG_APLL_SW_DIS_DELAY1_CFG_PLLDIG_AUTO_SWITCH_DELAY_MASK (0xFFFF0000U)
#define CSL_PLLDIG_CTRL_PLLDIG_APLL_SW_DIS_DELAY1_PLLDIG_APLL_SW_DIS_DELAY1_CFG_PLLDIG_AUTO_SWITCH_DELAY_SHIFT (0x00000010U)
#define CSL_PLLDIG_CTRL_PLLDIG_APLL_SW_DIS_DELAY1_PLLDIG_APLL_SW_DIS_DELAY1_CFG_PLLDIG_AUTO_SWITCH_DELAY_RESETVAL (0x00000FA0U)
#define CSL_PLLDIG_CTRL_PLLDIG_APLL_SW_DIS_DELAY1_PLLDIG_APLL_SW_DIS_DELAY1_CFG_PLLDIG_AUTO_SWITCH_DELAY_MAX (0x0000FFFFU)

#define CSL_PLLDIG_CTRL_PLLDIG_APLL_SW_DIS_DELAY1_RESETVAL                     (0x0FA00FA0U)

/* PLLDIG_APLL_SW_DIS_DELAY2 */

#define CSL_PLLDIG_CTRL_PLLDIG_APLL_SW_DIS_DELAY2_PLLDIG_APLL_SW_DIS_DELAY2_CFG_PLLDIG_DISABLE_DELAY_MASK (0x0000FFFFU)
#define CSL_PLLDIG_CTRL_PLLDIG_APLL_SW_DIS_DELAY2_PLLDIG_APLL_SW_DIS_DELAY2_CFG_PLLDIG_DISABLE_DELAY_SHIFT (0x00000000U)
#define CSL_PLLDIG_CTRL_PLLDIG_APLL_SW_DIS_DELAY2_PLLDIG_APLL_SW_DIS_DELAY2_CFG_PLLDIG_DISABLE_DELAY_RESETVAL (0x00000064U)
#define CSL_PLLDIG_CTRL_PLLDIG_APLL_SW_DIS_DELAY2_PLLDIG_APLL_SW_DIS_DELAY2_CFG_PLLDIG_DISABLE_DELAY_MAX (0x0000FFFFU)

#define CSL_PLLDIG_CTRL_PLLDIG_APLL_SW_DIS_DELAY2_PLLDIG_APLL_SW_DIS_DELAY2_CFG_APLL_DISABLE_DELAY_MASK (0xFFFF0000U)
#define CSL_PLLDIG_CTRL_PLLDIG_APLL_SW_DIS_DELAY2_PLLDIG_APLL_SW_DIS_DELAY2_CFG_APLL_DISABLE_DELAY_SHIFT (0x00000010U)
#define CSL_PLLDIG_CTRL_PLLDIG_APLL_SW_DIS_DELAY2_PLLDIG_APLL_SW_DIS_DELAY2_CFG_APLL_DISABLE_DELAY_RESETVAL (0x00000064U)
#define CSL_PLLDIG_CTRL_PLLDIG_APLL_SW_DIS_DELAY2_PLLDIG_APLL_SW_DIS_DELAY2_CFG_APLL_DISABLE_DELAY_MAX (0x0000FFFFU)

#define CSL_PLLDIG_CTRL_PLLDIG_APLL_SW_DIS_DELAY2_RESETVAL                     (0x00640064U)

/* PLLDIG_OVERRIDE */

#define CSL_PLLDIG_CTRL_PLLDIG_OVERRIDE_PLLDIG_OVERRIDE_CFG_SEL_OV_FINAL_PLLDIG_APLL_MUX_SEL_MASK (0x00000007U)
#define CSL_PLLDIG_CTRL_PLLDIG_OVERRIDE_PLLDIG_OVERRIDE_CFG_SEL_OV_FINAL_PLLDIG_APLL_MUX_SEL_SHIFT (0x00000000U)
#define CSL_PLLDIG_CTRL_PLLDIG_OVERRIDE_PLLDIG_OVERRIDE_CFG_SEL_OV_FINAL_PLLDIG_APLL_MUX_SEL_RESETVAL (0x00000000U)
#define CSL_PLLDIG_CTRL_PLLDIG_OVERRIDE_PLLDIG_OVERRIDE_CFG_SEL_OV_FINAL_PLLDIG_APLL_MUX_SEL_MAX (0x00000007U)

#define CSL_PLLDIG_CTRL_PLLDIG_OVERRIDE_PLLDIG_OVERRIDE_CFG_OV_FINAL_PLLDIG_APLL_MUX_SEL_MASK (0x00000038U)
#define CSL_PLLDIG_CTRL_PLLDIG_OVERRIDE_PLLDIG_OVERRIDE_CFG_OV_FINAL_PLLDIG_APLL_MUX_SEL_SHIFT (0x00000003U)
#define CSL_PLLDIG_CTRL_PLLDIG_OVERRIDE_PLLDIG_OVERRIDE_CFG_OV_FINAL_PLLDIG_APLL_MUX_SEL_RESETVAL (0x00000000U)
#define CSL_PLLDIG_CTRL_PLLDIG_OVERRIDE_PLLDIG_OVERRIDE_CFG_OV_FINAL_PLLDIG_APLL_MUX_SEL_MAX (0x00000007U)

#define CSL_PLLDIG_CTRL_PLLDIG_OVERRIDE_RESETVAL                               (0x00000000U)

/* PLLDIG_STATUS */

#define CSL_PLLDIG_CTRL_PLLDIG_STATUS_PLLDIG_STATUS_CLKM_XTAL_FREQ_MASK        (0x00000003U)
#define CSL_PLLDIG_CTRL_PLLDIG_STATUS_PLLDIG_STATUS_CLKM_XTAL_FREQ_SHIFT       (0x00000000U)
#define CSL_PLLDIG_CTRL_PLLDIG_STATUS_PLLDIG_STATUS_CLKM_XTAL_FREQ_RESETVAL    (0x00000000U)
#define CSL_PLLDIG_CTRL_PLLDIG_STATUS_PLLDIG_STATUS_CLKM_XTAL_FREQ_MAX         (0x00000003U)

#define CSL_PLLDIG_CTRL_PLLDIG_STATUS_PLLDIG_STATUS_PLLDIG_LOCKMON_MASK        (0x00000100U)
#define CSL_PLLDIG_CTRL_PLLDIG_STATUS_PLLDIG_STATUS_PLLDIG_LOCKMON_SHIFT       (0x00000008U)
#define CSL_PLLDIG_CTRL_PLLDIG_STATUS_PLLDIG_STATUS_PLLDIG_LOCKMON_RESETVAL    (0x00000000U)
#define CSL_PLLDIG_CTRL_PLLDIG_STATUS_PLLDIG_STATUS_PLLDIG_LOCKMON_MAX         (0x00000001U)

#define CSL_PLLDIG_CTRL_PLLDIG_STATUS_RESETVAL                                 (0x00000000U)

/* FAST_CLK_MUX_POSTDIV */

#define CSL_PLLDIG_CTRL_FAST_CLK_MUX_POSTDIV_FAST_CLK_MUX_POSTDIV_CURRDIVR_MASK (0x0000000FU)
#define CSL_PLLDIG_CTRL_FAST_CLK_MUX_POSTDIV_FAST_CLK_MUX_POSTDIV_CURRDIVR_SHIFT (0x00000000U)
#define CSL_PLLDIG_CTRL_FAST_CLK_MUX_POSTDIV_FAST_CLK_MUX_POSTDIV_CURRDIVR_RESETVAL (0x00000001U)
#define CSL_PLLDIG_CTRL_FAST_CLK_MUX_POSTDIV_FAST_CLK_MUX_POSTDIV_CURRDIVR_MAX (0x0000000FU)

#define CSL_PLLDIG_CTRL_FAST_CLK_MUX_POSTDIV_FAST_CLK_MUX_POSTDIV_DIVR_MASK    (0x0000FFF0U)
#define CSL_PLLDIG_CTRL_FAST_CLK_MUX_POSTDIV_FAST_CLK_MUX_POSTDIV_DIVR_SHIFT   (0x00000004U)
#define CSL_PLLDIG_CTRL_FAST_CLK_MUX_POSTDIV_FAST_CLK_MUX_POSTDIV_DIVR_RESETVAL (0x00000000U)
#define CSL_PLLDIG_CTRL_FAST_CLK_MUX_POSTDIV_FAST_CLK_MUX_POSTDIV_DIVR_MAX     (0x00000FFFU)

#define CSL_PLLDIG_CTRL_FAST_CLK_MUX_POSTDIV_RESETVAL                          (0x00000001U)

/* FAST_CLK_STATUS */

#define CSL_PLLDIG_CTRL_FAST_CLK_STATUS_FAST_CLK_STATUS_CURRCLK_MASK           (0x00000003U)
#define CSL_PLLDIG_CTRL_FAST_CLK_STATUS_FAST_CLK_STATUS_CURRCLK_SHIFT          (0x00000000U)
#define CSL_PLLDIG_CTRL_FAST_CLK_STATUS_FAST_CLK_STATUS_CURRCLK_RESETVAL       (0x00000001U)
#define CSL_PLLDIG_CTRL_FAST_CLK_STATUS_FAST_CLK_STATUS_CURRCLK_MAX            (0x00000003U)

#define CSL_PLLDIG_CTRL_FAST_CLK_STATUS_RESETVAL                               (0x00000001U)

/* LOCK0_KICK0 */

#define CSL_PLLDIG_CTRL_LOCK0_KICK0_LOCK0_KICK0_MASK                           (0xFFFFFFFFU)
#define CSL_PLLDIG_CTRL_LOCK0_KICK0_LOCK0_KICK0_SHIFT                          (0x00000000U)
#define CSL_PLLDIG_CTRL_LOCK0_KICK0_LOCK0_KICK0_RESETVAL                       (0x00000000U)
#define CSL_PLLDIG_CTRL_LOCK0_KICK0_LOCK0_KICK0_MAX                            (0xFFFFFFFFU)

#define CSL_PLLDIG_CTRL_LOCK0_KICK0_RESETVAL                                   (0x00000000U)

/* LOCK0_KICK1 */

#define CSL_PLLDIG_CTRL_LOCK0_KICK1_LOCK0_KICK1_MASK                           (0xFFFFFFFFU)
#define CSL_PLLDIG_CTRL_LOCK0_KICK1_LOCK0_KICK1_SHIFT                          (0x00000000U)
#define CSL_PLLDIG_CTRL_LOCK0_KICK1_LOCK0_KICK1_RESETVAL                       (0x00000000U)
#define CSL_PLLDIG_CTRL_LOCK0_KICK1_LOCK0_KICK1_MAX                            (0xFFFFFFFFU)

#define CSL_PLLDIG_CTRL_LOCK0_KICK1_RESETVAL                                   (0x00000000U)

/* INTR_RAW_STATUS */

#define CSL_PLLDIG_CTRL_INTR_RAW_STATUS_PROT_ERR_MASK                          (0x00000001U)
#define CSL_PLLDIG_CTRL_INTR_RAW_STATUS_PROT_ERR_SHIFT                         (0x00000000U)
#define CSL_PLLDIG_CTRL_INTR_RAW_STATUS_PROT_ERR_RESETVAL                      (0x00000000U)
#define CSL_PLLDIG_CTRL_INTR_RAW_STATUS_PROT_ERR_MAX                           (0x00000001U)

#define CSL_PLLDIG_CTRL_INTR_RAW_STATUS_ADDR_ERR_MASK                          (0x00000002U)
#define CSL_PLLDIG_CTRL_INTR_RAW_STATUS_ADDR_ERR_SHIFT                         (0x00000001U)
#define CSL_PLLDIG_CTRL_INTR_RAW_STATUS_ADDR_ERR_RESETVAL                      (0x00000000U)
#define CSL_PLLDIG_CTRL_INTR_RAW_STATUS_ADDR_ERR_MAX                           (0x00000001U)

#define CSL_PLLDIG_CTRL_INTR_RAW_STATUS_KICK_ERR_MASK                          (0x00000004U)
#define CSL_PLLDIG_CTRL_INTR_RAW_STATUS_KICK_ERR_SHIFT                         (0x00000002U)
#define CSL_PLLDIG_CTRL_INTR_RAW_STATUS_KICK_ERR_RESETVAL                      (0x00000000U)
#define CSL_PLLDIG_CTRL_INTR_RAW_STATUS_KICK_ERR_MAX                           (0x00000001U)

#define CSL_PLLDIG_CTRL_INTR_RAW_STATUS_PROXY_ERR_MASK                         (0x00000008U)
#define CSL_PLLDIG_CTRL_INTR_RAW_STATUS_PROXY_ERR_SHIFT                        (0x00000003U)
#define CSL_PLLDIG_CTRL_INTR_RAW_STATUS_PROXY_ERR_RESETVAL                     (0x00000000U)
#define CSL_PLLDIG_CTRL_INTR_RAW_STATUS_PROXY_ERR_MAX                          (0x00000001U)

#define CSL_PLLDIG_CTRL_INTR_RAW_STATUS_RESETVAL                               (0x00000000U)

/* INTR_ENABLED_STATUS_CLEAR */

#define CSL_PLLDIG_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROT_ERR_MASK        (0x00000001U)
#define CSL_PLLDIG_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROT_ERR_SHIFT       (0x00000000U)
#define CSL_PLLDIG_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROT_ERR_RESETVAL    (0x00000000U)
#define CSL_PLLDIG_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROT_ERR_MAX         (0x00000001U)

#define CSL_PLLDIG_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_ADDR_ERR_MASK        (0x00000002U)
#define CSL_PLLDIG_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_ADDR_ERR_SHIFT       (0x00000001U)
#define CSL_PLLDIG_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_ADDR_ERR_RESETVAL    (0x00000000U)
#define CSL_PLLDIG_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_ADDR_ERR_MAX         (0x00000001U)

#define CSL_PLLDIG_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_KICK_ERR_MASK        (0x00000004U)
#define CSL_PLLDIG_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_KICK_ERR_SHIFT       (0x00000002U)
#define CSL_PLLDIG_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_KICK_ERR_RESETVAL    (0x00000000U)
#define CSL_PLLDIG_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_KICK_ERR_MAX         (0x00000001U)

#define CSL_PLLDIG_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROXY_ERR_MASK       (0x00000008U)
#define CSL_PLLDIG_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROXY_ERR_SHIFT      (0x00000003U)
#define CSL_PLLDIG_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROXY_ERR_RESETVAL   (0x00000000U)
#define CSL_PLLDIG_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROXY_ERR_MAX        (0x00000001U)

#define CSL_PLLDIG_CTRL_INTR_ENABLED_STATUS_CLEAR_RESETVAL                     (0x00000000U)

/* INTR_ENABLE */

#define CSL_PLLDIG_CTRL_INTR_ENABLE_PROT_ERR_EN_MASK                           (0x00000001U)
#define CSL_PLLDIG_CTRL_INTR_ENABLE_PROT_ERR_EN_SHIFT                          (0x00000000U)
#define CSL_PLLDIG_CTRL_INTR_ENABLE_PROT_ERR_EN_RESETVAL                       (0x00000000U)
#define CSL_PLLDIG_CTRL_INTR_ENABLE_PROT_ERR_EN_MAX                            (0x00000001U)

#define CSL_PLLDIG_CTRL_INTR_ENABLE_ADDR_ERR_EN_MASK                           (0x00000002U)
#define CSL_PLLDIG_CTRL_INTR_ENABLE_ADDR_ERR_EN_SHIFT                          (0x00000001U)
#define CSL_PLLDIG_CTRL_INTR_ENABLE_ADDR_ERR_EN_RESETVAL                       (0x00000000U)
#define CSL_PLLDIG_CTRL_INTR_ENABLE_ADDR_ERR_EN_MAX                            (0x00000001U)

#define CSL_PLLDIG_CTRL_INTR_ENABLE_KICK_ERR_EN_MASK                           (0x00000004U)
#define CSL_PLLDIG_CTRL_INTR_ENABLE_KICK_ERR_EN_SHIFT                          (0x00000002U)
#define CSL_PLLDIG_CTRL_INTR_ENABLE_KICK_ERR_EN_RESETVAL                       (0x00000000U)
#define CSL_PLLDIG_CTRL_INTR_ENABLE_KICK_ERR_EN_MAX                            (0x00000001U)

#define CSL_PLLDIG_CTRL_INTR_ENABLE_PROXY_ERR_EN_MASK                          (0x00000008U)
#define CSL_PLLDIG_CTRL_INTR_ENABLE_PROXY_ERR_EN_SHIFT                         (0x00000003U)
#define CSL_PLLDIG_CTRL_INTR_ENABLE_PROXY_ERR_EN_RESETVAL                      (0x00000000U)
#define CSL_PLLDIG_CTRL_INTR_ENABLE_PROXY_ERR_EN_MAX                           (0x00000001U)

#define CSL_PLLDIG_CTRL_INTR_ENABLE_RESETVAL                                   (0x00000000U)

/* INTR_ENABLE_CLEAR */

#define CSL_PLLDIG_CTRL_INTR_ENABLE_CLEAR_PROT_ERR_EN_CLR_MASK                 (0x00000001U)
#define CSL_PLLDIG_CTRL_INTR_ENABLE_CLEAR_PROT_ERR_EN_CLR_SHIFT                (0x00000000U)
#define CSL_PLLDIG_CTRL_INTR_ENABLE_CLEAR_PROT_ERR_EN_CLR_RESETVAL             (0x00000000U)
#define CSL_PLLDIG_CTRL_INTR_ENABLE_CLEAR_PROT_ERR_EN_CLR_MAX                  (0x00000001U)

#define CSL_PLLDIG_CTRL_INTR_ENABLE_CLEAR_ADDR_ERR_EN_CLR_MASK                 (0x00000002U)
#define CSL_PLLDIG_CTRL_INTR_ENABLE_CLEAR_ADDR_ERR_EN_CLR_SHIFT                (0x00000001U)
#define CSL_PLLDIG_CTRL_INTR_ENABLE_CLEAR_ADDR_ERR_EN_CLR_RESETVAL             (0x00000000U)
#define CSL_PLLDIG_CTRL_INTR_ENABLE_CLEAR_ADDR_ERR_EN_CLR_MAX                  (0x00000001U)

#define CSL_PLLDIG_CTRL_INTR_ENABLE_CLEAR_KICK_ERR_EN_CLR_MASK                 (0x00000004U)
#define CSL_PLLDIG_CTRL_INTR_ENABLE_CLEAR_KICK_ERR_EN_CLR_SHIFT                (0x00000002U)
#define CSL_PLLDIG_CTRL_INTR_ENABLE_CLEAR_KICK_ERR_EN_CLR_RESETVAL             (0x00000000U)
#define CSL_PLLDIG_CTRL_INTR_ENABLE_CLEAR_KICK_ERR_EN_CLR_MAX                  (0x00000001U)

#define CSL_PLLDIG_CTRL_INTR_ENABLE_CLEAR_PROXY_ERR_EN_CLR_MASK                (0x00000008U)
#define CSL_PLLDIG_CTRL_INTR_ENABLE_CLEAR_PROXY_ERR_EN_CLR_SHIFT               (0x00000003U)
#define CSL_PLLDIG_CTRL_INTR_ENABLE_CLEAR_PROXY_ERR_EN_CLR_RESETVAL            (0x00000000U)
#define CSL_PLLDIG_CTRL_INTR_ENABLE_CLEAR_PROXY_ERR_EN_CLR_MAX                 (0x00000001U)

#define CSL_PLLDIG_CTRL_INTR_ENABLE_CLEAR_RESETVAL                             (0x00000000U)

/* EOI */

#define CSL_PLLDIG_CTRL_EOI_EOI_VECTOR_MASK                                    (0x000000FFU)
#define CSL_PLLDIG_CTRL_EOI_EOI_VECTOR_SHIFT                                   (0x00000000U)
#define CSL_PLLDIG_CTRL_EOI_EOI_VECTOR_RESETVAL                                (0x00000000U)
#define CSL_PLLDIG_CTRL_EOI_EOI_VECTOR_MAX                                     (0x000000FFU)

#define CSL_PLLDIG_CTRL_EOI_RESETVAL                                           (0x00000000U)

/* FAULT_ADDRESS */

#define CSL_PLLDIG_CTRL_FAULT_ADDRESS_FAULT_ADDR_MASK                          (0xFFFFFFFFU)
#define CSL_PLLDIG_CTRL_FAULT_ADDRESS_FAULT_ADDR_SHIFT                         (0x00000000U)
#define CSL_PLLDIG_CTRL_FAULT_ADDRESS_FAULT_ADDR_RESETVAL                      (0x00000000U)
#define CSL_PLLDIG_CTRL_FAULT_ADDRESS_FAULT_ADDR_MAX                           (0xFFFFFFFFU)

#define CSL_PLLDIG_CTRL_FAULT_ADDRESS_RESETVAL                                 (0x00000000U)

/* FAULT_TYPE_STATUS */

#define CSL_PLLDIG_CTRL_FAULT_TYPE_STATUS_FAULT_TYPE_MASK                      (0x0000003FU)
#define CSL_PLLDIG_CTRL_FAULT_TYPE_STATUS_FAULT_TYPE_SHIFT                     (0x00000000U)
#define CSL_PLLDIG_CTRL_FAULT_TYPE_STATUS_FAULT_TYPE_RESETVAL                  (0x00000000U)
#define CSL_PLLDIG_CTRL_FAULT_TYPE_STATUS_FAULT_TYPE_MAX                       (0x0000003FU)

#define CSL_PLLDIG_CTRL_FAULT_TYPE_STATUS_FAULT_NS_MASK                        (0x00000040U)
#define CSL_PLLDIG_CTRL_FAULT_TYPE_STATUS_FAULT_NS_SHIFT                       (0x00000006U)
#define CSL_PLLDIG_CTRL_FAULT_TYPE_STATUS_FAULT_NS_RESETVAL                    (0x00000000U)
#define CSL_PLLDIG_CTRL_FAULT_TYPE_STATUS_FAULT_NS_MAX                         (0x00000001U)

#define CSL_PLLDIG_CTRL_FAULT_TYPE_STATUS_RESETVAL                             (0x00000000U)

/* FAULT_ATTR_STATUS */

#define CSL_PLLDIG_CTRL_FAULT_ATTR_STATUS_FAULT_PRIVID_MASK                    (0x000000FFU)
#define CSL_PLLDIG_CTRL_FAULT_ATTR_STATUS_FAULT_PRIVID_SHIFT                   (0x00000000U)
#define CSL_PLLDIG_CTRL_FAULT_ATTR_STATUS_FAULT_PRIVID_RESETVAL                (0x00000000U)
#define CSL_PLLDIG_CTRL_FAULT_ATTR_STATUS_FAULT_PRIVID_MAX                     (0x000000FFU)

#define CSL_PLLDIG_CTRL_FAULT_ATTR_STATUS_FAULT_ROUTEID_MASK                   (0x000FFF00U)
#define CSL_PLLDIG_CTRL_FAULT_ATTR_STATUS_FAULT_ROUTEID_SHIFT                  (0x00000008U)
#define CSL_PLLDIG_CTRL_FAULT_ATTR_STATUS_FAULT_ROUTEID_RESETVAL               (0x00000000U)
#define CSL_PLLDIG_CTRL_FAULT_ATTR_STATUS_FAULT_ROUTEID_MAX                    (0x00000FFFU)

#define CSL_PLLDIG_CTRL_FAULT_ATTR_STATUS_FAULT_XID_MASK                       (0xFFF00000U)
#define CSL_PLLDIG_CTRL_FAULT_ATTR_STATUS_FAULT_XID_SHIFT                      (0x00000014U)
#define CSL_PLLDIG_CTRL_FAULT_ATTR_STATUS_FAULT_XID_RESETVAL                   (0x00000000U)
#define CSL_PLLDIG_CTRL_FAULT_ATTR_STATUS_FAULT_XID_MAX                        (0x00000FFFU)

#define CSL_PLLDIG_CTRL_FAULT_ATTR_STATUS_RESETVAL                             (0x00000000U)

/* FAULT_CLEAR */

#define CSL_PLLDIG_CTRL_FAULT_CLEAR_FAULT_CLR_MASK                             (0x00000001U)
#define CSL_PLLDIG_CTRL_FAULT_CLEAR_FAULT_CLR_SHIFT                            (0x00000000U)
#define CSL_PLLDIG_CTRL_FAULT_CLEAR_FAULT_CLR_RESETVAL                         (0x00000000U)
#define CSL_PLLDIG_CTRL_FAULT_CLEAR_FAULT_CLR_MAX                              (0x00000001U)

#define CSL_PLLDIG_CTRL_FAULT_CLEAR_RESETVAL                                   (0x00000000U)

#ifdef __cplusplus
}
#endif
#endif
