/********************************************************************
 * Copyright (C) 2023 Texas Instruments Incorporated.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *  Name        : cslr_fec_ctrl.h
*/
#ifndef CSLR_FEC_CTRL_H_
#define CSLR_FEC_CTRL_H_

#ifdef __cplusplus
extern "C"
{
#endif
#include <drivers/hw_include/cslr.h>
#include <stdint.h>

/**************************************************************************
* Hardware Region  :
**************************************************************************/


/**************************************************************************
* Register Overlay Structure
**************************************************************************/

typedef struct {
    volatile uint32_t PID;
    volatile uint32_t FESS_CTRL0;
    volatile uint32_t FESS_CTRL1;
    volatile uint32_t FESS_CTRL2;
    volatile uint32_t FESS_CTRL3;
    volatile uint32_t FECSS_DBG_ACK_CTRL;
    volatile uint32_t FECSS_CM3_ROM_ECLIPSE;
    volatile uint32_t FECSS_CM3_STATUS_REG;
    volatile uint32_t FECSS_SHARED_MEM_INIT;
    volatile uint32_t FECSS_SHARED_MEM_DONE;
    volatile uint32_t FECSS_SHARED_MEM_STATUS;
    volatile uint32_t FECSS_SHARED_MEM_CLK_GATE;
    volatile uint32_t FECSS_MEM_INIT_SLICE_SEL;
    volatile uint32_t FECSS_RAM_MEM_INIT;
    volatile uint32_t FECSS_RAM_MEM_DONE;
    volatile uint32_t FECSS_RAM_MEM_STATUS;
    volatile uint32_t FECSS_GPADC_MEM_INIT;
    volatile uint32_t FECSS_GPADC_MEM_DONE;
    volatile uint32_t FECSS_GPADC_MEM_STATUS;
    volatile uint32_t FECSS_TIMING_ENGINE_MEM_INIT;
    volatile uint32_t FECSS_TIMING_ENGINE_MEM_DONE;
    volatile uint32_t FECSS_TIMING_ENGINE_MEM_STATUS;
    volatile uint32_t FECSS_SW_INT;
    volatile uint32_t FECSS_IPC_RFS;
    volatile uint32_t FECSS_IPC_BUSY_INT0;
    volatile uint32_t FECSS_IPC_BUSY_INT1;
    volatile uint32_t FECSS_IPC_BUSY_INT2;
    volatile uint32_t FECSS_IPC_BUSY_INT3;
    volatile uint32_t FECSS_WIC_STAT_CLR;
    volatile uint32_t FECSS_WIC_STAT;
    volatile uint32_t FECSS_WIC_MASK;
    volatile uint32_t FECSS_WICEN;
    volatile uint32_t FECSS_FORCEFCLKACTIVE;
    volatile uint32_t FECSS_IRQ_REQ;
    volatile uint32_t FECSS_ERRAGG_MASK0;
    volatile uint32_t FECSS_ERRAGG_STATUS0;
    volatile uint32_t FECSS_ERRAGG_MASK1;
    volatile uint32_t FECSS_ERRAGG_STATUS1;
    volatile uint32_t FECSS_INTMASK1;
    volatile uint32_t FECSS_INTMASK2;
    volatile uint32_t CFG_TIMEOUT_PCR1;
    volatile uint32_t FESS_CTRL37;
    volatile uint32_t FESS_CTRL38;
    volatile uint32_t FESS_CTRL39;
    volatile uint32_t FESS_CTRL40;
    volatile uint32_t FESS_CTRL41;
    volatile uint32_t FESS_CTRL42;
    volatile uint32_t FESS_CTRL43;
    volatile uint32_t FESS_CTRL44;
    volatile uint32_t FESS_CTRL45;
    volatile uint32_t FESS_CTRL46;
    volatile uint32_t FESS_CTRL47;
    volatile uint32_t FESS_CTRL48;
    volatile uint32_t FESS_CTRL49;
    volatile uint32_t FESS_CTRL50;
    volatile uint32_t RESERVED0;
    volatile uint32_t APPSS_DYNAMIC_CLK_GATE_STATUS;
    volatile uint32_t FECSS_RAM_OWRITE_ERR;
    volatile uint32_t FECSS_RAM_OWRITE_ERR_ADDR;
    volatile uint32_t FECSS_SHRD_RAM_OWRITE_ERR;
    volatile uint32_t FECSS_SHRD_RAM_OWRITE_ERR_ADDR;
    volatile uint32_t FECSS_OWRITE_ERR_AGGR;
    volatile uint32_t HW_SPARE_RW0;
    volatile uint32_t HW_SPARE_RW1;
    volatile uint32_t CM3_CPU_HALT_HANDSHAKE;
    volatile uint8_t  Resv_4104[3844];
    volatile uint32_t LOCK0_KICK0;
    volatile uint32_t LOCK0_KICK1;
    volatile uint32_t INTR_RAW_STATUS;
    volatile uint32_t INTR_ENABLED_STATUS_CLEAR;
    volatile uint32_t INTR_ENABLE;
    volatile uint32_t INTR_ENABLE_CLEAR;
    volatile uint32_t EOI;
    volatile uint32_t FAULT_ADDRESS;
    volatile uint32_t FAULT_TYPE_STATUS;
    volatile uint32_t FAULT_ATTR_STATUS;
    volatile uint32_t FAULT_CLEAR;
} CSL_fec_ctrlRegs;


/**************************************************************************
* Register Macros
**************************************************************************/

#define CSL_FEC_CTRL_PID                                                       (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL0                                                (0x00000004U)
#define CSL_FEC_CTRL_FESS_CTRL1                                                (0x00000008U)
#define CSL_FEC_CTRL_FESS_CTRL2                                                (0x0000000CU)
#define CSL_FEC_CTRL_FESS_CTRL3                                                (0x00000010U)
#define CSL_FEC_CTRL_FECSS_DBG_ACK_CTRL                                        (0x00000014U)
#define CSL_FEC_CTRL_FECSS_CM3_ROM_ECLIPSE                                     (0x00000018U)
#define CSL_FEC_CTRL_FECSS_CM3_STATUS_REG                                      (0x0000001CU)
#define CSL_FEC_CTRL_FECSS_SHARED_MEM_INIT                                     (0x00000020U)
#define CSL_FEC_CTRL_FECSS_SHARED_MEM_DONE                                     (0x00000024U)
#define CSL_FEC_CTRL_FECSS_SHARED_MEM_STATUS                                   (0x00000028U)
#define CSL_FEC_CTRL_FECSS_SHARED_MEM_CLK_GATE                                 (0x0000002CU)
#define CSL_FEC_CTRL_FECSS_MEM_INIT_SLICE_SEL                                  (0x00000030U)
#define CSL_FEC_CTRL_FECSS_RAM_MEM_INIT                                        (0x00000034U)
#define CSL_FEC_CTRL_FECSS_RAM_MEM_DONE                                        (0x00000038U)
#define CSL_FEC_CTRL_FECSS_RAM_MEM_STATUS                                      (0x0000003CU)
#define CSL_FEC_CTRL_FECSS_GPADC_MEM_INIT                                      (0x00000040U)
#define CSL_FEC_CTRL_FECSS_GPADC_MEM_DONE                                      (0x00000044U)
#define CSL_FEC_CTRL_FECSS_GPADC_MEM_STATUS                                    (0x00000048U)
#define CSL_FEC_CTRL_FECSS_TIMING_ENGINE_MEM_INIT                              (0x0000004CU)
#define CSL_FEC_CTRL_FECSS_TIMING_ENGINE_MEM_DONE                              (0x00000050U)
#define CSL_FEC_CTRL_FECSS_TIMING_ENGINE_MEM_STATUS                            (0x00000054U)
#define CSL_FEC_CTRL_FECSS_SW_INT                                              (0x00000058U)
#define CSL_FEC_CTRL_FECSS_IPC_RFS                                             (0x0000005CU)
#define CSL_FEC_CTRL_FECSS_IPC_BUSY_INT0                                       (0x00000060U)
#define CSL_FEC_CTRL_FECSS_IPC_BUSY_INT1                                       (0x00000064U)
#define CSL_FEC_CTRL_FECSS_IPC_BUSY_INT2                                       (0x00000068U)
#define CSL_FEC_CTRL_FECSS_IPC_BUSY_INT3                                       (0x0000006CU)
#define CSL_FEC_CTRL_FECSS_WIC_STAT_CLR                                        (0x00000070U)
#define CSL_FEC_CTRL_FECSS_WIC_STAT                                            (0x00000074U)
#define CSL_FEC_CTRL_FECSS_WIC_MASK                                            (0x00000078U)
#define CSL_FEC_CTRL_FECSS_WICEN                                               (0x0000007CU)
#define CSL_FEC_CTRL_FECSS_FORCEFCLKACTIVE                                     (0x00000080U)
#define CSL_FEC_CTRL_FECSS_IRQ_REQ                                             (0x00000084U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0                                        (0x00000088U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0                                      (0x0000008CU)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK1                                        (0x00000090U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS1                                      (0x00000094U)
#define CSL_FEC_CTRL_FECSS_INTMASK1                                            (0x00000098U)
#define CSL_FEC_CTRL_FECSS_INTMASK2                                            (0x0000009CU)
#define CSL_FEC_CTRL_CFG_TIMEOUT_PCR1                                          (0x000000A0U)
#define CSL_FEC_CTRL_FESS_CTRL37                                               (0x000000A4U)
#define CSL_FEC_CTRL_FESS_CTRL38                                               (0x000000A8U)
#define CSL_FEC_CTRL_FESS_CTRL39                                               (0x000000ACU)
#define CSL_FEC_CTRL_FESS_CTRL40                                               (0x000000B0U)
#define CSL_FEC_CTRL_FESS_CTRL41                                               (0x000000B4U)
#define CSL_FEC_CTRL_FESS_CTRL42                                               (0x000000B8U)
#define CSL_FEC_CTRL_FESS_CTRL43                                               (0x000000BCU)
#define CSL_FEC_CTRL_FESS_CTRL44                                               (0x000000C0U)
#define CSL_FEC_CTRL_FESS_CTRL45                                               (0x000000C4U)
#define CSL_FEC_CTRL_FESS_CTRL46                                               (0x000000C8U)
#define CSL_FEC_CTRL_FESS_CTRL47                                               (0x000000CCU)
#define CSL_FEC_CTRL_FESS_CTRL48                                               (0x000000D0U)
#define CSL_FEC_CTRL_FESS_CTRL49                                               (0x000000D4U)
#define CSL_FEC_CTRL_FESS_CTRL50                                               (0x000000D8U)
#define CSL_FEC_CTRL_RESERVED0                                                 (0x000000DCU)
#define CSL_FEC_CTRL_APPSS_DYNAMIC_CLK_GATE_STATUS                             (0x000000E0U)
#define CSL_FEC_CTRL_FECSS_RAM_OWRITE_ERR                                      (0x000000E4U)
#define CSL_FEC_CTRL_FECSS_RAM_OWRITE_ERR_ADDR                                 (0x000000E8U)
#define CSL_FEC_CTRL_FECSS_SHRD_RAM_OWRITE_ERR                                 (0x000000ECU)
#define CSL_FEC_CTRL_FECSS_SHRD_RAM_OWRITE_ERR_ADDR                            (0x000000F0U)
#define CSL_FEC_CTRL_FECSS_OWRITE_ERR_AGGR                                     (0x000000F4U)
#define CSL_FEC_CTRL_HW_SPARE_RW0                                              (0x000000F8U)
#define CSL_FEC_CTRL_HW_SPARE_RW1                                              (0x000000FCU)
#define CSL_FEC_CTRL_CM3_CPU_HALT_HANDSHAKE                                    (0x00000100U)
#define CSL_FEC_CTRL_LOCK0_KICK0                                               (0x00001008U)
#define CSL_FEC_CTRL_LOCK0_KICK1                                               (0x0000100CU)
#define CSL_FEC_CTRL_INTR_RAW_STATUS                                           (0x00001010U)
#define CSL_FEC_CTRL_INTR_ENABLED_STATUS_CLEAR                                 (0x00001014U)
#define CSL_FEC_CTRL_INTR_ENABLE                                               (0x00001018U)
#define CSL_FEC_CTRL_INTR_ENABLE_CLEAR                                         (0x0000101CU)
#define CSL_FEC_CTRL_EOI                                                       (0x00001020U)
#define CSL_FEC_CTRL_FAULT_ADDRESS                                             (0x00001024U)
#define CSL_FEC_CTRL_FAULT_TYPE_STATUS                                         (0x00001028U)
#define CSL_FEC_CTRL_FAULT_ATTR_STATUS                                         (0x0000102CU)
#define CSL_FEC_CTRL_FAULT_CLEAR                                               (0x00001030U)

/**************************************************************************
* Field Definition Macros
**************************************************************************/


/* PID */

#define CSL_FEC_CTRL_PID_PID_MINOR_MASK                                        (0x0000003FU)
#define CSL_FEC_CTRL_PID_PID_MINOR_SHIFT                                       (0x00000000U)
#define CSL_FEC_CTRL_PID_PID_MINOR_RESETVAL                                    (0x00000014U)
#define CSL_FEC_CTRL_PID_PID_MINOR_MAX                                         (0x0000003FU)

#define CSL_FEC_CTRL_PID_PID_CUSTOM_MASK                                       (0x000000C0U)
#define CSL_FEC_CTRL_PID_PID_CUSTOM_SHIFT                                      (0x00000006U)
#define CSL_FEC_CTRL_PID_PID_CUSTOM_RESETVAL                                   (0x00000000U)
#define CSL_FEC_CTRL_PID_PID_CUSTOM_MAX                                        (0x00000003U)

#define CSL_FEC_CTRL_PID_PID_MAJOR_MASK                                        (0x00000700U)
#define CSL_FEC_CTRL_PID_PID_MAJOR_SHIFT                                       (0x00000008U)
#define CSL_FEC_CTRL_PID_PID_MAJOR_RESETVAL                                    (0x00000002U)
#define CSL_FEC_CTRL_PID_PID_MAJOR_MAX                                         (0x00000007U)

#define CSL_FEC_CTRL_PID_PID_MISC_MASK                                         (0x0000F800U)
#define CSL_FEC_CTRL_PID_PID_MISC_SHIFT                                        (0x0000000BU)
#define CSL_FEC_CTRL_PID_PID_MISC_RESETVAL                                     (0x00000000U)
#define CSL_FEC_CTRL_PID_PID_MISC_MAX                                          (0x0000001FU)

#define CSL_FEC_CTRL_PID_PID_MSB16_MASK                                        (0xFFFF0000U)
#define CSL_FEC_CTRL_PID_PID_MSB16_SHIFT                                       (0x00000010U)
#define CSL_FEC_CTRL_PID_PID_MSB16_RESETVAL                                    (0x00006180U)
#define CSL_FEC_CTRL_PID_PID_MSB16_MAX                                         (0x0000FFFFU)

#define CSL_FEC_CTRL_PID_RESETVAL                                              (0x61800214U)

/* FESS_CTRL0 */

#define CSL_FEC_CTRL_FESS_CTRL0_FESS_CTRL0_FESS_CTRL0_MASK                     (0xFFFFFFFFU)
#define CSL_FEC_CTRL_FESS_CTRL0_FESS_CTRL0_FESS_CTRL0_SHIFT                    (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL0_FESS_CTRL0_FESS_CTRL0_RESETVAL                 (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL0_FESS_CTRL0_FESS_CTRL0_MAX                      (0xFFFFFFFFU)

#define CSL_FEC_CTRL_FESS_CTRL0_RESETVAL                                       (0x00000000U)

/* FESS_CTRL1 */

#define CSL_FEC_CTRL_FESS_CTRL1_FESS_CTRL1_FESS_CTRL1_MASK                     (0xFFFFFFFFU)
#define CSL_FEC_CTRL_FESS_CTRL1_FESS_CTRL1_FESS_CTRL1_SHIFT                    (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL1_FESS_CTRL1_FESS_CTRL1_RESETVAL                 (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL1_FESS_CTRL1_FESS_CTRL1_MAX                      (0xFFFFFFFFU)

#define CSL_FEC_CTRL_FESS_CTRL1_RESETVAL                                       (0x00000000U)

/* FESS_CTRL2 */

#define CSL_FEC_CTRL_FESS_CTRL2_FESS_CTRL2_FESS_CTRL2_MASK                     (0xFFFFFFFFU)
#define CSL_FEC_CTRL_FESS_CTRL2_FESS_CTRL2_FESS_CTRL2_SHIFT                    (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL2_FESS_CTRL2_FESS_CTRL2_RESETVAL                 (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL2_FESS_CTRL2_FESS_CTRL2_MAX                      (0xFFFFFFFFU)

#define CSL_FEC_CTRL_FESS_CTRL2_RESETVAL                                       (0x00000000U)

/* FESS_CTRL3 */

#define CSL_FEC_CTRL_FESS_CTRL3_FESS_CTRL3_FESS_CTRL3_MASK                     (0xFFFFFFFFU)
#define CSL_FEC_CTRL_FESS_CTRL3_FESS_CTRL3_FESS_CTRL3_SHIFT                    (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL3_FESS_CTRL3_FESS_CTRL3_RESETVAL                 (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL3_FESS_CTRL3_FESS_CTRL3_MAX                      (0xFFFFFFFFU)

#define CSL_FEC_CTRL_FESS_CTRL3_RESETVAL                                       (0x00000000U)

/* FECSS_DBG_ACK_CTRL */

#define CSL_FEC_CTRL_FECSS_DBG_ACK_CTRL_FECSS_DBG_ACK_CTRL_RTI_MASK            (0x00000007U)
#define CSL_FEC_CTRL_FECSS_DBG_ACK_CTRL_FECSS_DBG_ACK_CTRL_RTI_SHIFT           (0x00000000U)
#define CSL_FEC_CTRL_FECSS_DBG_ACK_CTRL_FECSS_DBG_ACK_CTRL_RTI_RESETVAL        (0x00000000U)
#define CSL_FEC_CTRL_FECSS_DBG_ACK_CTRL_FECSS_DBG_ACK_CTRL_RTI_MAX             (0x00000007U)

#define CSL_FEC_CTRL_FECSS_DBG_ACK_CTRL_RESETVAL                               (0x00000000U)

/* FECSS_CM3_ROM_ECLIPSE */

#define CSL_FEC_CTRL_FECSS_CM3_ROM_ECLIPSE_FECSS_CM3_ROM_ECLIPSE_MEMSWAP_MASK  (0x00000007U)
#define CSL_FEC_CTRL_FECSS_CM3_ROM_ECLIPSE_FECSS_CM3_ROM_ECLIPSE_MEMSWAP_SHIFT (0x00000000U)
#define CSL_FEC_CTRL_FECSS_CM3_ROM_ECLIPSE_FECSS_CM3_ROM_ECLIPSE_MEMSWAP_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_CM3_ROM_ECLIPSE_FECSS_CM3_ROM_ECLIPSE_MEMSWAP_MAX   (0x00000007U)

#define CSL_FEC_CTRL_FECSS_CM3_ROM_ECLIPSE_FECSS_CM3_ROM_ECLIPSE_MEMSWAP_WAIT_MASK (0x00000038U)
#define CSL_FEC_CTRL_FECSS_CM3_ROM_ECLIPSE_FECSS_CM3_ROM_ECLIPSE_MEMSWAP_WAIT_SHIFT (0x00000003U)
#define CSL_FEC_CTRL_FECSS_CM3_ROM_ECLIPSE_FECSS_CM3_ROM_ECLIPSE_MEMSWAP_WAIT_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_CM3_ROM_ECLIPSE_FECSS_CM3_ROM_ECLIPSE_MEMSWAP_WAIT_MAX (0x00000007U)

#define CSL_FEC_CTRL_FECSS_CM3_ROM_ECLIPSE_RESETVAL                            (0x00000000U)

/* FECSS_CM3_STATUS_REG */

#define CSL_FEC_CTRL_FECSS_CM3_STATUS_REG_FECSS_CM3_STATUS_REG_MEMSWAP_MASK    (0x00000001U)
#define CSL_FEC_CTRL_FECSS_CM3_STATUS_REG_FECSS_CM3_STATUS_REG_MEMSWAP_SHIFT   (0x00000000U)
#define CSL_FEC_CTRL_FECSS_CM3_STATUS_REG_FECSS_CM3_STATUS_REG_MEMSWAP_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_CM3_STATUS_REG_FECSS_CM3_STATUS_REG_MEMSWAP_MAX     (0x00000001U)

#define CSL_FEC_CTRL_FECSS_CM3_STATUS_REG_RESETVAL                             (0x00000000U)

/* FECSS_SHARED_MEM_INIT */

#define CSL_FEC_CTRL_FECSS_SHARED_MEM_INIT_FECSS_SHARED_MEM_INIT_MEM_INIT_MASK (0x00000001U)
#define CSL_FEC_CTRL_FECSS_SHARED_MEM_INIT_FECSS_SHARED_MEM_INIT_MEM_INIT_SHIFT (0x00000000U)
#define CSL_FEC_CTRL_FECSS_SHARED_MEM_INIT_FECSS_SHARED_MEM_INIT_MEM_INIT_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_SHARED_MEM_INIT_FECSS_SHARED_MEM_INIT_MEM_INIT_MAX  (0x00000001U)

#define CSL_FEC_CTRL_FECSS_SHARED_MEM_INIT_RESETVAL                            (0x00000000U)

/* FECSS_SHARED_MEM_DONE */

#define CSL_FEC_CTRL_FECSS_SHARED_MEM_DONE_FECSS_SHARED_MEM_DONE_MEM_INIT_DONE_MASK (0x00000001U)
#define CSL_FEC_CTRL_FECSS_SHARED_MEM_DONE_FECSS_SHARED_MEM_DONE_MEM_INIT_DONE_SHIFT (0x00000000U)
#define CSL_FEC_CTRL_FECSS_SHARED_MEM_DONE_FECSS_SHARED_MEM_DONE_MEM_INIT_DONE_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_SHARED_MEM_DONE_FECSS_SHARED_MEM_DONE_MEM_INIT_DONE_MAX (0x00000001U)

#define CSL_FEC_CTRL_FECSS_SHARED_MEM_DONE_RESETVAL                            (0x00000000U)

/* FECSS_SHARED_MEM_STATUS */

#define CSL_FEC_CTRL_FECSS_SHARED_MEM_STATUS_FECSS_SHARED_MEM_STATUS_MEM_INIT_STATUS_MASK (0x00000001U)
#define CSL_FEC_CTRL_FECSS_SHARED_MEM_STATUS_FECSS_SHARED_MEM_STATUS_MEM_INIT_STATUS_SHIFT (0x00000000U)
#define CSL_FEC_CTRL_FECSS_SHARED_MEM_STATUS_FECSS_SHARED_MEM_STATUS_MEM_INIT_STATUS_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_SHARED_MEM_STATUS_FECSS_SHARED_MEM_STATUS_MEM_INIT_STATUS_MAX (0x00000001U)

#define CSL_FEC_CTRL_FECSS_SHARED_MEM_STATUS_RESETVAL                          (0x00000000U)

/* FECSS_SHARED_MEM_CLK_GATE */

#define CSL_FEC_CTRL_FECSS_SHARED_MEM_CLK_GATE_FECSS_SHARED_MEM_CLK_GATE_HWA_ENABLE_MASK (0x00000001U)
#define CSL_FEC_CTRL_FECSS_SHARED_MEM_CLK_GATE_FECSS_SHARED_MEM_CLK_GATE_HWA_ENABLE_SHIFT (0x00000000U)
#define CSL_FEC_CTRL_FECSS_SHARED_MEM_CLK_GATE_FECSS_SHARED_MEM_CLK_GATE_HWA_ENABLE_RESETVAL (0x00000001U)
#define CSL_FEC_CTRL_FECSS_SHARED_MEM_CLK_GATE_FECSS_SHARED_MEM_CLK_GATE_HWA_ENABLE_MAX (0x00000001U)

#define CSL_FEC_CTRL_FECSS_SHARED_MEM_CLK_GATE_FECSS_SHARED_MEM_CLK_GATE_FEC_ENABLE_MASK (0x00000002U)
#define CSL_FEC_CTRL_FECSS_SHARED_MEM_CLK_GATE_FECSS_SHARED_MEM_CLK_GATE_FEC_ENABLE_SHIFT (0x00000001U)
#define CSL_FEC_CTRL_FECSS_SHARED_MEM_CLK_GATE_FECSS_SHARED_MEM_CLK_GATE_FEC_ENABLE_RESETVAL (0x00000001U)
#define CSL_FEC_CTRL_FECSS_SHARED_MEM_CLK_GATE_FECSS_SHARED_MEM_CLK_GATE_FEC_ENABLE_MAX (0x00000001U)

#define CSL_FEC_CTRL_FECSS_SHARED_MEM_CLK_GATE_RESETVAL                        (0x00000003U)

/* FECSS_MEM_INIT_SLICE_SEL */

#define CSL_FEC_CTRL_FECSS_MEM_INIT_SLICE_SEL_FECSS_MEM_INIT_SLICE_SEL_CFG_MEM_INIT_SLICE_SEL_MASK (0x00000003U)
#define CSL_FEC_CTRL_FECSS_MEM_INIT_SLICE_SEL_FECSS_MEM_INIT_SLICE_SEL_CFG_MEM_INIT_SLICE_SEL_SHIFT (0x00000000U)
#define CSL_FEC_CTRL_FECSS_MEM_INIT_SLICE_SEL_FECSS_MEM_INIT_SLICE_SEL_CFG_MEM_INIT_SLICE_SEL_RESETVAL (0x00000003U)
#define CSL_FEC_CTRL_FECSS_MEM_INIT_SLICE_SEL_FECSS_MEM_INIT_SLICE_SEL_CFG_MEM_INIT_SLICE_SEL_MAX (0x00000003U)

#define CSL_FEC_CTRL_FECSS_MEM_INIT_SLICE_SEL_RESETVAL                         (0x00000003U)

/* FECSS_RAM_MEM_INIT */

#define CSL_FEC_CTRL_FECSS_RAM_MEM_INIT_FECSS_RAM_MEM_INIT_MEM_INIT_MASK       (0x00000001U)
#define CSL_FEC_CTRL_FECSS_RAM_MEM_INIT_FECSS_RAM_MEM_INIT_MEM_INIT_SHIFT      (0x00000000U)
#define CSL_FEC_CTRL_FECSS_RAM_MEM_INIT_FECSS_RAM_MEM_INIT_MEM_INIT_RESETVAL   (0x00000000U)
#define CSL_FEC_CTRL_FECSS_RAM_MEM_INIT_FECSS_RAM_MEM_INIT_MEM_INIT_MAX        (0x00000001U)

#define CSL_FEC_CTRL_FECSS_RAM_MEM_INIT_RESETVAL                               (0x00000000U)

/* FECSS_RAM_MEM_DONE */

#define CSL_FEC_CTRL_FECSS_RAM_MEM_DONE_FECSS_RAM_MEM_DONE_MEM_INIT_DONE_MASK  (0x00000001U)
#define CSL_FEC_CTRL_FECSS_RAM_MEM_DONE_FECSS_RAM_MEM_DONE_MEM_INIT_DONE_SHIFT (0x00000000U)
#define CSL_FEC_CTRL_FECSS_RAM_MEM_DONE_FECSS_RAM_MEM_DONE_MEM_INIT_DONE_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_RAM_MEM_DONE_FECSS_RAM_MEM_DONE_MEM_INIT_DONE_MAX   (0x00000001U)

#define CSL_FEC_CTRL_FECSS_RAM_MEM_DONE_RESETVAL                               (0x00000000U)

/* FECSS_RAM_MEM_STATUS */

#define CSL_FEC_CTRL_FECSS_RAM_MEM_STATUS_FECSS_RAM_MEM_STATUS_MEM_INIT_STATUS_MASK (0x00000001U)
#define CSL_FEC_CTRL_FECSS_RAM_MEM_STATUS_FECSS_RAM_MEM_STATUS_MEM_INIT_STATUS_SHIFT (0x00000000U)
#define CSL_FEC_CTRL_FECSS_RAM_MEM_STATUS_FECSS_RAM_MEM_STATUS_MEM_INIT_STATUS_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_RAM_MEM_STATUS_FECSS_RAM_MEM_STATUS_MEM_INIT_STATUS_MAX (0x00000001U)

#define CSL_FEC_CTRL_FECSS_RAM_MEM_STATUS_RESETVAL                             (0x00000000U)

/* FECSS_GPADC_MEM_INIT */

#define CSL_FEC_CTRL_FECSS_GPADC_MEM_INIT_FECSS_GPADC_MEM_INIT_MEM_INIT_MASK   (0x00000001U)
#define CSL_FEC_CTRL_FECSS_GPADC_MEM_INIT_FECSS_GPADC_MEM_INIT_MEM_INIT_SHIFT  (0x00000000U)
#define CSL_FEC_CTRL_FECSS_GPADC_MEM_INIT_FECSS_GPADC_MEM_INIT_MEM_INIT_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_GPADC_MEM_INIT_FECSS_GPADC_MEM_INIT_MEM_INIT_MAX    (0x00000001U)

#define CSL_FEC_CTRL_FECSS_GPADC_MEM_INIT_RESETVAL                             (0x00000000U)

/* FECSS_GPADC_MEM_DONE */

#define CSL_FEC_CTRL_FECSS_GPADC_MEM_DONE_FECSS_GPADC_MEM_DONE_MEM_INIT_DONE_MASK (0x00000001U)
#define CSL_FEC_CTRL_FECSS_GPADC_MEM_DONE_FECSS_GPADC_MEM_DONE_MEM_INIT_DONE_SHIFT (0x00000000U)
#define CSL_FEC_CTRL_FECSS_GPADC_MEM_DONE_FECSS_GPADC_MEM_DONE_MEM_INIT_DONE_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_GPADC_MEM_DONE_FECSS_GPADC_MEM_DONE_MEM_INIT_DONE_MAX (0x00000001U)

#define CSL_FEC_CTRL_FECSS_GPADC_MEM_DONE_RESETVAL                             (0x00000000U)

/* FECSS_GPADC_MEM_STATUS */

#define CSL_FEC_CTRL_FECSS_GPADC_MEM_STATUS_FECSS_GPADC_MEM_STATUS_MEM_INIT_STATUS_MASK (0x00000001U)
#define CSL_FEC_CTRL_FECSS_GPADC_MEM_STATUS_FECSS_GPADC_MEM_STATUS_MEM_INIT_STATUS_SHIFT (0x00000000U)
#define CSL_FEC_CTRL_FECSS_GPADC_MEM_STATUS_FECSS_GPADC_MEM_STATUS_MEM_INIT_STATUS_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_GPADC_MEM_STATUS_FECSS_GPADC_MEM_STATUS_MEM_INIT_STATUS_MAX (0x00000001U)

#define CSL_FEC_CTRL_FECSS_GPADC_MEM_STATUS_RESETVAL                           (0x00000000U)

/* FECSS_TIMING_ENGINE_MEM_INIT */

#define CSL_FEC_CTRL_FECSS_TIMING_ENGINE_MEM_INIT_FECSS_TIMING_ENGINE_MEM_INIT_MEM_INIT_MASK (0x00000001U)
#define CSL_FEC_CTRL_FECSS_TIMING_ENGINE_MEM_INIT_FECSS_TIMING_ENGINE_MEM_INIT_MEM_INIT_SHIFT (0x00000000U)
#define CSL_FEC_CTRL_FECSS_TIMING_ENGINE_MEM_INIT_FECSS_TIMING_ENGINE_MEM_INIT_MEM_INIT_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_TIMING_ENGINE_MEM_INIT_FECSS_TIMING_ENGINE_MEM_INIT_MEM_INIT_MAX (0x00000001U)

#define CSL_FEC_CTRL_FECSS_TIMING_ENGINE_MEM_INIT_RESETVAL                     (0x00000000U)

/* FECSS_TIMING_ENGINE_MEM_DONE */

#define CSL_FEC_CTRL_FECSS_TIMING_ENGINE_MEM_DONE_FECSS_TIMING_ENGINE_MEM_DONE_MEM_INIT_DONE_MASK (0x00000001U)
#define CSL_FEC_CTRL_FECSS_TIMING_ENGINE_MEM_DONE_FECSS_TIMING_ENGINE_MEM_DONE_MEM_INIT_DONE_SHIFT (0x00000000U)
#define CSL_FEC_CTRL_FECSS_TIMING_ENGINE_MEM_DONE_FECSS_TIMING_ENGINE_MEM_DONE_MEM_INIT_DONE_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_TIMING_ENGINE_MEM_DONE_FECSS_TIMING_ENGINE_MEM_DONE_MEM_INIT_DONE_MAX (0x00000001U)

#define CSL_FEC_CTRL_FECSS_TIMING_ENGINE_MEM_DONE_RESETVAL                     (0x00000000U)

/* FECSS_TIMING_ENGINE_MEM_STATUS */

#define CSL_FEC_CTRL_FECSS_TIMING_ENGINE_MEM_STATUS_FECSS_TIMING_ENGINE_MEM_STATUS_MEM_INIT_STATUS_MASK (0x00000001U)
#define CSL_FEC_CTRL_FECSS_TIMING_ENGINE_MEM_STATUS_FECSS_TIMING_ENGINE_MEM_STATUS_MEM_INIT_STATUS_SHIFT (0x00000000U)
#define CSL_FEC_CTRL_FECSS_TIMING_ENGINE_MEM_STATUS_FECSS_TIMING_ENGINE_MEM_STATUS_MEM_INIT_STATUS_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_TIMING_ENGINE_MEM_STATUS_FECSS_TIMING_ENGINE_MEM_STATUS_MEM_INIT_STATUS_MAX (0x00000001U)

#define CSL_FEC_CTRL_FECSS_TIMING_ENGINE_MEM_STATUS_RESETVAL                   (0x00000000U)

/* FECSS_SW_INT */

#define CSL_FEC_CTRL_FECSS_SW_INT_FECSS_SW_INT_PULSE_MASK                      (0x0000000FU)
#define CSL_FEC_CTRL_FECSS_SW_INT_FECSS_SW_INT_PULSE_SHIFT                     (0x00000000U)
#define CSL_FEC_CTRL_FECSS_SW_INT_FECSS_SW_INT_PULSE_RESETVAL                  (0x00000000U)
#define CSL_FEC_CTRL_FECSS_SW_INT_FECSS_SW_INT_PULSE_MAX                       (0x0000000FU)

#define CSL_FEC_CTRL_FECSS_SW_INT_RESETVAL                                     (0x00000000U)

/* FECSS_IPC_RFS */

#define CSL_FEC_CTRL_FECSS_IPC_RFS_FECSS_IPC_RFS_FEC_INTR_MASK                 (0x0000000FU)
#define CSL_FEC_CTRL_FECSS_IPC_RFS_FECSS_IPC_RFS_FEC_INTR_SHIFT                (0x00000000U)
#define CSL_FEC_CTRL_FECSS_IPC_RFS_FECSS_IPC_RFS_FEC_INTR_RESETVAL             (0x00000000U)
#define CSL_FEC_CTRL_FECSS_IPC_RFS_FECSS_IPC_RFS_FEC_INTR_MAX                  (0x0000000FU)

#define CSL_FEC_CTRL_FECSS_IPC_RFS_FECSS_IPC_RFS_RESPONSE_MASK                 (0xFFFFFFF0U)
#define CSL_FEC_CTRL_FECSS_IPC_RFS_FECSS_IPC_RFS_RESPONSE_SHIFT                (0x00000004U)
#define CSL_FEC_CTRL_FECSS_IPC_RFS_FECSS_IPC_RFS_RESPONSE_RESETVAL             (0x00000000U)
#define CSL_FEC_CTRL_FECSS_IPC_RFS_FECSS_IPC_RFS_RESPONSE_MAX                  (0x0FFFFFFFU)

#define CSL_FEC_CTRL_FECSS_IPC_RFS_RESETVAL                                    (0x00000000U)

/* FECSS_IPC_BUSY_INT0 */

#define CSL_FEC_CTRL_FECSS_IPC_BUSY_INT0_FECSS_IPC_BUSY_INT0_FLAG_MASK         (0x00000001U)
#define CSL_FEC_CTRL_FECSS_IPC_BUSY_INT0_FECSS_IPC_BUSY_INT0_FLAG_SHIFT        (0x00000000U)
#define CSL_FEC_CTRL_FECSS_IPC_BUSY_INT0_FECSS_IPC_BUSY_INT0_FLAG_RESETVAL     (0x00000000U)
#define CSL_FEC_CTRL_FECSS_IPC_BUSY_INT0_FECSS_IPC_BUSY_INT0_FLAG_MAX          (0x00000001U)

#define CSL_FEC_CTRL_FECSS_IPC_BUSY_INT0_RESETVAL                              (0x00000000U)

/* FECSS_IPC_BUSY_INT1 */

#define CSL_FEC_CTRL_FECSS_IPC_BUSY_INT1_FECSS_IPC_BUSY_INT1_FLAG_MASK         (0x00000001U)
#define CSL_FEC_CTRL_FECSS_IPC_BUSY_INT1_FECSS_IPC_BUSY_INT1_FLAG_SHIFT        (0x00000000U)
#define CSL_FEC_CTRL_FECSS_IPC_BUSY_INT1_FECSS_IPC_BUSY_INT1_FLAG_RESETVAL     (0x00000000U)
#define CSL_FEC_CTRL_FECSS_IPC_BUSY_INT1_FECSS_IPC_BUSY_INT1_FLAG_MAX          (0x00000001U)

#define CSL_FEC_CTRL_FECSS_IPC_BUSY_INT1_RESETVAL                              (0x00000000U)

/* FECSS_IPC_BUSY_INT2 */

#define CSL_FEC_CTRL_FECSS_IPC_BUSY_INT2_FECSS_IPC_BUSY_INT2_FLAG_MASK         (0x00000001U)
#define CSL_FEC_CTRL_FECSS_IPC_BUSY_INT2_FECSS_IPC_BUSY_INT2_FLAG_SHIFT        (0x00000000U)
#define CSL_FEC_CTRL_FECSS_IPC_BUSY_INT2_FECSS_IPC_BUSY_INT2_FLAG_RESETVAL     (0x00000000U)
#define CSL_FEC_CTRL_FECSS_IPC_BUSY_INT2_FECSS_IPC_BUSY_INT2_FLAG_MAX          (0x00000001U)

#define CSL_FEC_CTRL_FECSS_IPC_BUSY_INT2_RESETVAL                              (0x00000000U)

/* FECSS_IPC_BUSY_INT3 */

#define CSL_FEC_CTRL_FECSS_IPC_BUSY_INT3_FECSS_IPC_BUSY_INT3_FLAG_MASK         (0x00000001U)
#define CSL_FEC_CTRL_FECSS_IPC_BUSY_INT3_FECSS_IPC_BUSY_INT3_FLAG_SHIFT        (0x00000000U)
#define CSL_FEC_CTRL_FECSS_IPC_BUSY_INT3_FECSS_IPC_BUSY_INT3_FLAG_RESETVAL     (0x00000000U)
#define CSL_FEC_CTRL_FECSS_IPC_BUSY_INT3_FECSS_IPC_BUSY_INT3_FLAG_MAX          (0x00000001U)

#define CSL_FEC_CTRL_FECSS_IPC_BUSY_INT3_RESETVAL                              (0x00000000U)

/* FECSS_WIC_STAT_CLR */

#define CSL_FEC_CTRL_FECSS_WIC_STAT_CLR_FECSS_WIC_STAT_CLR_FECSS_WIC_STAT_CLR_MASK (0xFFFFFFFFU)
#define CSL_FEC_CTRL_FECSS_WIC_STAT_CLR_FECSS_WIC_STAT_CLR_FECSS_WIC_STAT_CLR_SHIFT (0x00000000U)
#define CSL_FEC_CTRL_FECSS_WIC_STAT_CLR_FECSS_WIC_STAT_CLR_FECSS_WIC_STAT_CLR_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_WIC_STAT_CLR_FECSS_WIC_STAT_CLR_FECSS_WIC_STAT_CLR_MAX (0xFFFFFFFFU)

#define CSL_FEC_CTRL_FECSS_WIC_STAT_CLR_RESETVAL                               (0x00000000U)

/* FECSS_WIC_STAT */

#define CSL_FEC_CTRL_FECSS_WIC_STAT_FECSS_WIC_STAT_FECSS_WIC_STAT_MASK         (0xFFFFFFFFU)
#define CSL_FEC_CTRL_FECSS_WIC_STAT_FECSS_WIC_STAT_FECSS_WIC_STAT_SHIFT        (0x00000000U)
#define CSL_FEC_CTRL_FECSS_WIC_STAT_FECSS_WIC_STAT_FECSS_WIC_STAT_RESETVAL     (0x00000000U)
#define CSL_FEC_CTRL_FECSS_WIC_STAT_FECSS_WIC_STAT_FECSS_WIC_STAT_MAX          (0xFFFFFFFFU)

#define CSL_FEC_CTRL_FECSS_WIC_STAT_RESETVAL                                   (0x00000000U)

/* FECSS_WIC_MASK */

#define CSL_FEC_CTRL_FECSS_WIC_MASK_FECSS_WIC_MASK_FECSS_WIC_MASK_MASK         (0xFFFFFFFFU)
#define CSL_FEC_CTRL_FECSS_WIC_MASK_FECSS_WIC_MASK_FECSS_WIC_MASK_SHIFT        (0x00000000U)
#define CSL_FEC_CTRL_FECSS_WIC_MASK_FECSS_WIC_MASK_FECSS_WIC_MASK_RESETVAL     (0x00000000U)
#define CSL_FEC_CTRL_FECSS_WIC_MASK_FECSS_WIC_MASK_FECSS_WIC_MASK_MAX          (0xFFFFFFFFU)

#define CSL_FEC_CTRL_FECSS_WIC_MASK_RESETVAL                                   (0x00000000U)

/* FECSS_WICEN */

#define CSL_FEC_CTRL_FECSS_WICEN_FECSS_WICEN_FECSS_WICEN_MASK                  (0x00000001U)
#define CSL_FEC_CTRL_FECSS_WICEN_FECSS_WICEN_FECSS_WICEN_SHIFT                 (0x00000000U)
#define CSL_FEC_CTRL_FECSS_WICEN_FECSS_WICEN_FECSS_WICEN_RESETVAL              (0x00000001U)
#define CSL_FEC_CTRL_FECSS_WICEN_FECSS_WICEN_FECSS_WICEN_MAX                   (0x00000001U)

#define CSL_FEC_CTRL_FECSS_WICEN_RESETVAL                                      (0x00000001U)

/* FECSS_FORCEFCLKACTIVE */

#define CSL_FEC_CTRL_FECSS_FORCEFCLKACTIVE_FECSS_FORCEFCLKACTIVE_FECSS_FORCEFCLKACTIVE_MASK (0x00000001U)
#define CSL_FEC_CTRL_FECSS_FORCEFCLKACTIVE_FECSS_FORCEFCLKACTIVE_FECSS_FORCEFCLKACTIVE_SHIFT (0x00000000U)
#define CSL_FEC_CTRL_FECSS_FORCEFCLKACTIVE_FECSS_FORCEFCLKACTIVE_FECSS_FORCEFCLKACTIVE_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_FORCEFCLKACTIVE_FECSS_FORCEFCLKACTIVE_FECSS_FORCEFCLKACTIVE_MAX (0x00000001U)

#define CSL_FEC_CTRL_FECSS_FORCEFCLKACTIVE_RESETVAL                            (0x00000000U)

/* FECSS_IRQ_REQ */

#define CSL_FEC_CTRL_FECSS_IRQ_REQ_FECSS_IRQ_REQ_SELECT_MASK                   (0xFFFFFFFFU)
#define CSL_FEC_CTRL_FECSS_IRQ_REQ_FECSS_IRQ_REQ_SELECT_SHIFT                  (0x00000000U)
#define CSL_FEC_CTRL_FECSS_IRQ_REQ_FECSS_IRQ_REQ_SELECT_RESETVAL               (0x00000000U)
#define CSL_FEC_CTRL_FECSS_IRQ_REQ_FECSS_IRQ_REQ_SELECT_MAX                    (0xFFFFFFFFU)

#define CSL_FEC_CTRL_FECSS_IRQ_REQ_RESETVAL                                    (0x00000000U)

/* FECSS_ERRAGG_MASK0 */

#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_RCM_RD_MASK     (0x00000001U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_RCM_RD_SHIFT    (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_RCM_RD_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_RCM_RD_MAX      (0x00000001U)

#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_RCM_WR_MASK     (0x00000002U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_RCM_WR_SHIFT    (0x00000001U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_RCM_WR_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_RCM_WR_MAX      (0x00000001U)

#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_RADAR_CFG_RD_MASK   (0x00000004U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_RADAR_CFG_RD_SHIFT  (0x00000002U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_RADAR_CFG_RD_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_RADAR_CFG_RD_MAX    (0x00000001U)

#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_RADAR_CFG_WR_MASK   (0x00000008U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_RADAR_CFG_WR_SHIFT  (0x00000003U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_RADAR_CFG_WR_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_RADAR_CFG_WR_MAX    (0x00000001U)

#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_TIMING_ENGINE_RD_MASK (0x00000010U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_TIMING_ENGINE_RD_SHIFT (0x00000004U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_TIMING_ENGINE_RD_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_TIMING_ENGINE_RD_MAX (0x00000001U)

#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_TIMING_ENGINE_WR_MASK (0x00000020U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_TIMING_ENGINE_WR_SHIFT (0x00000005U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_TIMING_ENGINE_WR_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_TIMING_ENGINE_WR_MAX (0x00000001U)

#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_CTRL_RD_MASK    (0x00000040U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_CTRL_RD_SHIFT   (0x00000006U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_CTRL_RD_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_CTRL_RD_MAX     (0x00000001U)

#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_CTRL_WR_MASK    (0x00000080U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_CTRL_WR_SHIFT   (0x00000007U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_CTRL_WR_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_CTRL_WR_MAX     (0x00000001U)

#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_ANA_RD_MASK     (0x00000100U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_ANA_RD_SHIFT    (0x00000008U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_ANA_RD_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_ANA_RD_MAX      (0x00000001U)

#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_ANA_WR_MASK     (0x00000200U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_ANA_WR_SHIFT    (0x00000009U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_ANA_WR_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_ANA_WR_MAX      (0x00000001U)

#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_MPU_RD_MASK     (0x00000400U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_MPU_RD_SHIFT    (0x0000000AU)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_MPU_RD_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_MPU_RD_MAX      (0x00000001U)

#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_AHB_WR_MASK     (0x00000800U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_AHB_WR_SHIFT    (0x0000000BU)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_AHB_WR_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_AHB_WR_MAX      (0x00000001U)

#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_SHARED_MEM_ERR_MASK (0x00001000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_SHARED_MEM_ERR_SHIFT (0x0000000CU)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_SHARED_MEM_ERR_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_SHARED_MEM_ERR_MAX (0x00000001U)

#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_AHB_SLV_WR_MASK (0x00002000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_AHB_SLV_WR_SHIFT (0x0000000DU)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_AHB_SLV_WR_RESETVAL (0x00000001U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_AHB_SLV_WR_MAX  (0x00000001U)

#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_AHB_SLV_RD_MASK (0x00004000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_AHB_SLV_RD_SHIFT (0x0000000EU)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_AHB_SLV_RD_RESETVAL (0x00000001U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_FECSS_ERRAGG_MASK0_FEC_AHB_SLV_RD_MAX  (0x00000001U)

#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK0_RESETVAL                               (0x00006000U)

/* FECSS_ERRAGG_STATUS0 */

#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_RCM_RD_MASK (0x00000001U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_RCM_RD_SHIFT (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_RCM_RD_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_RCM_RD_MAX  (0x00000001U)

#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_RCM_WR_MASK (0x00000002U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_RCM_WR_SHIFT (0x00000001U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_RCM_WR_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_RCM_WR_MAX  (0x00000001U)

#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_RADAR_CFG_RD_MASK (0x00000004U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_RADAR_CFG_RD_SHIFT (0x00000002U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_RADAR_CFG_RD_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_RADAR_CFG_RD_MAX (0x00000001U)

#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_RADAR_CFG_WR_MASK (0x00000008U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_RADAR_CFG_WR_SHIFT (0x00000003U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_RADAR_CFG_WR_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_RADAR_CFG_WR_MAX (0x00000001U)

#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_TIMING_ENGINE_RD_MASK (0x00000010U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_TIMING_ENGINE_RD_SHIFT (0x00000004U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_TIMING_ENGINE_RD_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_TIMING_ENGINE_RD_MAX (0x00000001U)

#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_TIMING_ENGINE_WR_MASK (0x00000020U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_TIMING_ENGINE_WR_SHIFT (0x00000005U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_TIMING_ENGINE_WR_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_TIMING_ENGINE_WR_MAX (0x00000001U)

#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_CTRL_RD_MASK (0x00000040U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_CTRL_RD_SHIFT (0x00000006U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_CTRL_RD_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_CTRL_RD_MAX (0x00000001U)

#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_CTRL_WR_MASK (0x00000080U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_CTRL_WR_SHIFT (0x00000007U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_CTRL_WR_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_CTRL_WR_MAX (0x00000001U)

#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_ANA_RD_MASK (0x00000100U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_ANA_RD_SHIFT (0x00000008U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_ANA_RD_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_ANA_RD_MAX  (0x00000001U)

#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_ANA_WR_MASK (0x00000200U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_ANA_WR_SHIFT (0x00000009U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_ANA_WR_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_ANA_WR_MAX  (0x00000001U)

#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_MPU_RD_MASK (0x00000400U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_MPU_RD_SHIFT (0x0000000AU)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_MPU_RD_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_MPU_RD_MAX  (0x00000001U)

#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_AHB_WR_MASK (0x00000800U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_AHB_WR_SHIFT (0x0000000BU)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_AHB_WR_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_AHB_WR_MAX  (0x00000001U)

#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_SHARED_MEM_ERR_MASK (0x00001000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_SHARED_MEM_ERR_SHIFT (0x0000000CU)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_SHARED_MEM_ERR_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_SHARED_MEM_ERR_MAX (0x00000001U)

#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_AHB_SLV_WR_MASK (0x00002000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_AHB_SLV_WR_SHIFT (0x0000000DU)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_AHB_SLV_WR_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_AHB_SLV_WR_MAX (0x00000001U)

#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_AHB_SLV_RD_MASK (0x00004000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_AHB_SLV_RD_SHIFT (0x0000000EU)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_AHB_SLV_RD_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_FECSS_ERRAGG_STATUS0_FEC_AHB_SLV_RD_MAX (0x00000001U)

#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS0_RESETVAL                             (0x00000000U)

/* FECSS_ERRAGG_MASK1 */

#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK1_FECSS_ERRAGG_MASK1_SET_MASK            (0xFFFFFFFFU)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK1_FECSS_ERRAGG_MASK1_SET_SHIFT           (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK1_FECSS_ERRAGG_MASK1_SET_RESETVAL        (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK1_FECSS_ERRAGG_MASK1_SET_MAX             (0xFFFFFFFFU)

#define CSL_FEC_CTRL_FECSS_ERRAGG_MASK1_RESETVAL                               (0x00000000U)

/* FECSS_ERRAGG_STATUS1 */

#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS1_FECSS_ERRAGG_STATUS1_SET_MASK        (0xFFFFFFFFU)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS1_FECSS_ERRAGG_STATUS1_SET_SHIFT       (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS1_FECSS_ERRAGG_STATUS1_SET_RESETVAL    (0x00000000U)
#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS1_FECSS_ERRAGG_STATUS1_SET_MAX         (0xFFFFFFFFU)

#define CSL_FEC_CTRL_FECSS_ERRAGG_STATUS1_RESETVAL                             (0x00000000U)

/* FECSS_INTMASK1 */

#define CSL_FEC_CTRL_FECSS_INTMASK1_FECSS_INTMASK1_SET_MASK                    (0xFFFFFFFFU)
#define CSL_FEC_CTRL_FECSS_INTMASK1_FECSS_INTMASK1_SET_SHIFT                   (0x00000000U)
#define CSL_FEC_CTRL_FECSS_INTMASK1_FECSS_INTMASK1_SET_RESETVAL                (0x00000000U)
#define CSL_FEC_CTRL_FECSS_INTMASK1_FECSS_INTMASK1_SET_MAX                     (0xFFFFFFFFU)

#define CSL_FEC_CTRL_FECSS_INTMASK1_RESETVAL                                   (0x00000000U)

/* FECSS_INTMASK2 */

#define CSL_FEC_CTRL_FECSS_INTMASK2_FECSS_INTMASK2_SET_MASK                    (0xFFFFFFFFU)
#define CSL_FEC_CTRL_FECSS_INTMASK2_FECSS_INTMASK2_SET_SHIFT                   (0x00000000U)
#define CSL_FEC_CTRL_FECSS_INTMASK2_FECSS_INTMASK2_SET_RESETVAL                (0x00000000U)
#define CSL_FEC_CTRL_FECSS_INTMASK2_FECSS_INTMASK2_SET_MAX                     (0xFFFFFFFFU)

#define CSL_FEC_CTRL_FECSS_INTMASK2_RESETVAL                                   (0x00000000U)

/* CFG_TIMEOUT_PCR1 */

#define CSL_FEC_CTRL_CFG_TIMEOUT_PCR1_CFG_TIMEOUT_PCR1_VALUE_MASK              (0xFFFFFFFFU)
#define CSL_FEC_CTRL_CFG_TIMEOUT_PCR1_CFG_TIMEOUT_PCR1_VALUE_SHIFT             (0x00000000U)
#define CSL_FEC_CTRL_CFG_TIMEOUT_PCR1_CFG_TIMEOUT_PCR1_VALUE_RESETVAL          (0x00000FFFU)
#define CSL_FEC_CTRL_CFG_TIMEOUT_PCR1_CFG_TIMEOUT_PCR1_VALUE_MAX               (0xFFFFFFFFU)

#define CSL_FEC_CTRL_CFG_TIMEOUT_PCR1_RESETVAL                                 (0x00000FFFU)

/* FESS_CTRL37 */

#define CSL_FEC_CTRL_FESS_CTRL37_FESS_CTRL37_FESS_CTRL37_MASK                  (0xFFFFFFFFU)
#define CSL_FEC_CTRL_FESS_CTRL37_FESS_CTRL37_FESS_CTRL37_SHIFT                 (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL37_FESS_CTRL37_FESS_CTRL37_RESETVAL              (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL37_FESS_CTRL37_FESS_CTRL37_MAX                   (0xFFFFFFFFU)

#define CSL_FEC_CTRL_FESS_CTRL37_RESETVAL                                      (0x00000000U)

/* FESS_CTRL38 */

#define CSL_FEC_CTRL_FESS_CTRL38_FESS_CTRL38_FESS_CTRL38_MASK                  (0x00000001U)
#define CSL_FEC_CTRL_FESS_CTRL38_FESS_CTRL38_FESS_CTRL38_SHIFT                 (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL38_FESS_CTRL38_FESS_CTRL38_RESETVAL              (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL38_FESS_CTRL38_FESS_CTRL38_MAX                   (0x00000001U)

#define CSL_FEC_CTRL_FESS_CTRL38_RESETVAL                                      (0x00000000U)

/* FESS_CTRL39 */

#define CSL_FEC_CTRL_FESS_CTRL39_FESS_CTRL39_FESS_CTRL39_MASK                  (0x00000001U)
#define CSL_FEC_CTRL_FESS_CTRL39_FESS_CTRL39_FESS_CTRL39_SHIFT                 (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL39_FESS_CTRL39_FESS_CTRL39_RESETVAL              (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL39_FESS_CTRL39_FESS_CTRL39_MAX                   (0x00000001U)

#define CSL_FEC_CTRL_FESS_CTRL39_RESETVAL                                      (0x00000000U)

/* FESS_CTRL40 */

#define CSL_FEC_CTRL_FESS_CTRL40_FESS_CTRL40_FESS_CTRL40_MASK                  (0x00000001U)
#define CSL_FEC_CTRL_FESS_CTRL40_FESS_CTRL40_FESS_CTRL40_SHIFT                 (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL40_FESS_CTRL40_FESS_CTRL40_RESETVAL              (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL40_FESS_CTRL40_FESS_CTRL40_MAX                   (0x00000001U)

#define CSL_FEC_CTRL_FESS_CTRL40_RESETVAL                                      (0x00000000U)

/* FESS_CTRL41 */

#define CSL_FEC_CTRL_FESS_CTRL41_FESS_CTRL41_FESS_CTRL41_MASK                  (0x00000001U)
#define CSL_FEC_CTRL_FESS_CTRL41_FESS_CTRL41_FESS_CTRL41_SHIFT                 (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL41_FESS_CTRL41_FESS_CTRL41_RESETVAL              (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL41_FESS_CTRL41_FESS_CTRL41_MAX                   (0x00000001U)

#define CSL_FEC_CTRL_FESS_CTRL41_RESETVAL                                      (0x00000000U)

/* FESS_CTRL42 */

#define CSL_FEC_CTRL_FESS_CTRL42_FESS_CTRL42_FESS_CTRL42_MASK                  (0x00000001U)
#define CSL_FEC_CTRL_FESS_CTRL42_FESS_CTRL42_FESS_CTRL42_SHIFT                 (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL42_FESS_CTRL42_FESS_CTRL42_RESETVAL              (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL42_FESS_CTRL42_FESS_CTRL42_MAX                   (0x00000001U)

#define CSL_FEC_CTRL_FESS_CTRL42_RESETVAL                                      (0x00000000U)

/* FESS_CTRL43 */

#define CSL_FEC_CTRL_FESS_CTRL43_FESS_CTRL43_FESS_CTRL43_MASK                  (0x00000001U)
#define CSL_FEC_CTRL_FESS_CTRL43_FESS_CTRL43_FESS_CTRL43_SHIFT                 (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL43_FESS_CTRL43_FESS_CTRL43_RESETVAL              (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL43_FESS_CTRL43_FESS_CTRL43_MAX                   (0x00000001U)

#define CSL_FEC_CTRL_FESS_CTRL43_RESETVAL                                      (0x00000000U)

/* FESS_CTRL44 */

#define CSL_FEC_CTRL_FESS_CTRL44_FESS_CTRL44_FESS_CTRL44_MASK                  (0x00000001U)
#define CSL_FEC_CTRL_FESS_CTRL44_FESS_CTRL44_FESS_CTRL44_SHIFT                 (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL44_FESS_CTRL44_FESS_CTRL44_RESETVAL              (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL44_FESS_CTRL44_FESS_CTRL44_MAX                   (0x00000001U)

#define CSL_FEC_CTRL_FESS_CTRL44_RESETVAL                                      (0x00000000U)

/* FESS_CTRL45 */

#define CSL_FEC_CTRL_FESS_CTRL45_FESS_CTRL45_FESS_CTRL45_MASK                  (0x00000001U)
#define CSL_FEC_CTRL_FESS_CTRL45_FESS_CTRL45_FESS_CTRL45_SHIFT                 (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL45_FESS_CTRL45_FESS_CTRL45_RESETVAL              (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL45_FESS_CTRL45_FESS_CTRL45_MAX                   (0x00000001U)

#define CSL_FEC_CTRL_FESS_CTRL45_RESETVAL                                      (0x00000000U)

/* FESS_CTRL46 */

#define CSL_FEC_CTRL_FESS_CTRL46_FESS_CTRL46_FESS_CTRL46_MASK                  (0x00000001U)
#define CSL_FEC_CTRL_FESS_CTRL46_FESS_CTRL46_FESS_CTRL46_SHIFT                 (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL46_FESS_CTRL46_FESS_CTRL46_RESETVAL              (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL46_FESS_CTRL46_FESS_CTRL46_MAX                   (0x00000001U)

#define CSL_FEC_CTRL_FESS_CTRL46_RESETVAL                                      (0x00000000U)

/* FESS_CTRL47 */

#define CSL_FEC_CTRL_FESS_CTRL47_FESS_CTRL47_FESS_CTRL47_MASK                  (0x00010000U)
#define CSL_FEC_CTRL_FESS_CTRL47_FESS_CTRL47_FESS_CTRL47_SHIFT                 (0x00000010U)
#define CSL_FEC_CTRL_FESS_CTRL47_FESS_CTRL47_FESS_CTRL47_RESETVAL              (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL47_FESS_CTRL47_FESS_CTRL47_MAX                   (0x00000001U)

#define CSL_FEC_CTRL_FESS_CTRL47_RESETVAL                                      (0x00000000U)

/* FESS_CTRL48 */

#define CSL_FEC_CTRL_FESS_CTRL48_FESS_CTRL48_FESS_CTRL48_MASK                  (0x00000001U)
#define CSL_FEC_CTRL_FESS_CTRL48_FESS_CTRL48_FESS_CTRL48_SHIFT                 (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL48_FESS_CTRL48_FESS_CTRL48_RESETVAL              (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL48_FESS_CTRL48_FESS_CTRL48_MAX                   (0x00000001U)

#define CSL_FEC_CTRL_FESS_CTRL48_RESETVAL                                      (0x00000000U)

/* FESS_CTRL49 */

#define CSL_FEC_CTRL_FESS_CTRL49_FESS_CTRL49_FESS_CTRL49_MASK                  (0x00010000U)
#define CSL_FEC_CTRL_FESS_CTRL49_FESS_CTRL49_FESS_CTRL49_SHIFT                 (0x00000010U)
#define CSL_FEC_CTRL_FESS_CTRL49_FESS_CTRL49_FESS_CTRL49_RESETVAL              (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL49_FESS_CTRL49_FESS_CTRL49_MAX                   (0x00000001U)

#define CSL_FEC_CTRL_FESS_CTRL49_RESETVAL                                      (0x00000000U)

/* FESS_CTRL50 */

#define CSL_FEC_CTRL_FESS_CTRL50_FESS_CTRL50_FESS_CTRL50_MASK                  (0x00000001U)
#define CSL_FEC_CTRL_FESS_CTRL50_FESS_CTRL50_FESS_CTRL50_SHIFT                 (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL50_FESS_CTRL50_FESS_CTRL50_RESETVAL              (0x00000000U)
#define CSL_FEC_CTRL_FESS_CTRL50_FESS_CTRL50_FESS_CTRL50_MAX                   (0x00000001U)

#define CSL_FEC_CTRL_FESS_CTRL50_RESETVAL                                      (0x00000000U)

/* RESERVED0 */

#define CSL_FEC_CTRL_RESERVED0_RESERVED0_RESERVED_MASK                         (0x0000FFFFU)
#define CSL_FEC_CTRL_RESERVED0_RESERVED0_RESERVED_SHIFT                        (0x00000000U)
#define CSL_FEC_CTRL_RESERVED0_RESERVED0_RESERVED_RESETVAL                     (0x00000000U)
#define CSL_FEC_CTRL_RESERVED0_RESERVED0_RESERVED_MAX                          (0x0000FFFFU)

#define CSL_FEC_CTRL_RESERVED0_RESETVAL                                        (0x00000000U)

/* APPSS_DYNAMIC_CLK_GATE_STATUS */

#define CSL_FEC_CTRL_APPSS_DYNAMIC_CLK_GATE_STATUS_APPSS_DYNAMIC_CLK_GATE_STATUS_XBARA_MASK (0x00000001U)
#define CSL_FEC_CTRL_APPSS_DYNAMIC_CLK_GATE_STATUS_APPSS_DYNAMIC_CLK_GATE_STATUS_XBARA_SHIFT (0x00000000U)
#define CSL_FEC_CTRL_APPSS_DYNAMIC_CLK_GATE_STATUS_APPSS_DYNAMIC_CLK_GATE_STATUS_XBARA_RESETVAL (0x00000001U)
#define CSL_FEC_CTRL_APPSS_DYNAMIC_CLK_GATE_STATUS_APPSS_DYNAMIC_CLK_GATE_STATUS_XBARA_MAX (0x00000001U)

#define CSL_FEC_CTRL_APPSS_DYNAMIC_CLK_GATE_STATUS_APPSS_DYNAMIC_CLK_GATE_STATUS_TPTC1_MASK (0x00000002U)
#define CSL_FEC_CTRL_APPSS_DYNAMIC_CLK_GATE_STATUS_APPSS_DYNAMIC_CLK_GATE_STATUS_TPTC1_SHIFT (0x00000001U)
#define CSL_FEC_CTRL_APPSS_DYNAMIC_CLK_GATE_STATUS_APPSS_DYNAMIC_CLK_GATE_STATUS_TPTC1_RESETVAL (0x00000001U)
#define CSL_FEC_CTRL_APPSS_DYNAMIC_CLK_GATE_STATUS_APPSS_DYNAMIC_CLK_GATE_STATUS_TPTC1_MAX (0x00000001U)

#define CSL_FEC_CTRL_APPSS_DYNAMIC_CLK_GATE_STATUS_APPSS_DYNAMIC_CLK_GATE_STATUS_TPTC2_MASK (0x00000004U)
#define CSL_FEC_CTRL_APPSS_DYNAMIC_CLK_GATE_STATUS_APPSS_DYNAMIC_CLK_GATE_STATUS_TPTC2_SHIFT (0x00000002U)
#define CSL_FEC_CTRL_APPSS_DYNAMIC_CLK_GATE_STATUS_APPSS_DYNAMIC_CLK_GATE_STATUS_TPTC2_RESETVAL (0x00000001U)
#define CSL_FEC_CTRL_APPSS_DYNAMIC_CLK_GATE_STATUS_APPSS_DYNAMIC_CLK_GATE_STATUS_TPTC2_MAX (0x00000001U)

#define CSL_FEC_CTRL_APPSS_DYNAMIC_CLK_GATE_STATUS_RESETVAL                    (0x00000007U)

/* FECSS_RAM_OWRITE_ERR */

#define CSL_FEC_CTRL_FECSS_RAM_OWRITE_ERR_FECSS_RAM_OWRITE_ERR_ERR_MASK        (0x00000001U)
#define CSL_FEC_CTRL_FECSS_RAM_OWRITE_ERR_FECSS_RAM_OWRITE_ERR_ERR_SHIFT       (0x00000000U)
#define CSL_FEC_CTRL_FECSS_RAM_OWRITE_ERR_FECSS_RAM_OWRITE_ERR_ERR_RESETVAL    (0x00000000U)
#define CSL_FEC_CTRL_FECSS_RAM_OWRITE_ERR_FECSS_RAM_OWRITE_ERR_ERR_MAX         (0x00000001U)

#define CSL_FEC_CTRL_FECSS_RAM_OWRITE_ERR_RESETVAL                             (0x00000000U)

/* FECSS_RAM_OWRITE_ERR_ADDR */

#define CSL_FEC_CTRL_FECSS_RAM_OWRITE_ERR_ADDR_FECSS_RAM_OWRITE_ERR_ADDR_ADDRESS_MASK (0xFFFFFFFFU)
#define CSL_FEC_CTRL_FECSS_RAM_OWRITE_ERR_ADDR_FECSS_RAM_OWRITE_ERR_ADDR_ADDRESS_SHIFT (0x00000000U)
#define CSL_FEC_CTRL_FECSS_RAM_OWRITE_ERR_ADDR_FECSS_RAM_OWRITE_ERR_ADDR_ADDRESS_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_RAM_OWRITE_ERR_ADDR_FECSS_RAM_OWRITE_ERR_ADDR_ADDRESS_MAX (0xFFFFFFFFU)

#define CSL_FEC_CTRL_FECSS_RAM_OWRITE_ERR_ADDR_RESETVAL                        (0x00000000U)

/* FECSS_SHRD_RAM_OWRITE_ERR */

#define CSL_FEC_CTRL_FECSS_SHRD_RAM_OWRITE_ERR_FECSS_SHRD_RAM_OWRITE_ERR_ERR_MASK (0x00000001U)
#define CSL_FEC_CTRL_FECSS_SHRD_RAM_OWRITE_ERR_FECSS_SHRD_RAM_OWRITE_ERR_ERR_SHIFT (0x00000000U)
#define CSL_FEC_CTRL_FECSS_SHRD_RAM_OWRITE_ERR_FECSS_SHRD_RAM_OWRITE_ERR_ERR_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_SHRD_RAM_OWRITE_ERR_FECSS_SHRD_RAM_OWRITE_ERR_ERR_MAX (0x00000001U)

#define CSL_FEC_CTRL_FECSS_SHRD_RAM_OWRITE_ERR_RESETVAL                        (0x00000000U)

/* FECSS_SHRD_RAM_OWRITE_ERR_ADDR */

#define CSL_FEC_CTRL_FECSS_SHRD_RAM_OWRITE_ERR_ADDR_FECSS_SHRD_RAM_OWRITE_ERR_ADDR_ADDRESS_MASK (0xFFFFFFFFU)
#define CSL_FEC_CTRL_FECSS_SHRD_RAM_OWRITE_ERR_ADDR_FECSS_SHRD_RAM_OWRITE_ERR_ADDR_ADDRESS_SHIFT (0x00000000U)
#define CSL_FEC_CTRL_FECSS_SHRD_RAM_OWRITE_ERR_ADDR_FECSS_SHRD_RAM_OWRITE_ERR_ADDR_ADDRESS_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_FECSS_SHRD_RAM_OWRITE_ERR_ADDR_FECSS_SHRD_RAM_OWRITE_ERR_ADDR_ADDRESS_MAX (0xFFFFFFFFU)

#define CSL_FEC_CTRL_FECSS_SHRD_RAM_OWRITE_ERR_ADDR_RESETVAL                   (0x00000000U)

/* FECSS_OWRITE_ERR_AGGR */

#define CSL_FEC_CTRL_FECSS_OWRITE_ERR_AGGR_FECSS_OWRITE_ERR_AGGR_ERR_MASK      (0x00000001U)
#define CSL_FEC_CTRL_FECSS_OWRITE_ERR_AGGR_FECSS_OWRITE_ERR_AGGR_ERR_SHIFT     (0x00000000U)
#define CSL_FEC_CTRL_FECSS_OWRITE_ERR_AGGR_FECSS_OWRITE_ERR_AGGR_ERR_RESETVAL  (0x00000000U)
#define CSL_FEC_CTRL_FECSS_OWRITE_ERR_AGGR_FECSS_OWRITE_ERR_AGGR_ERR_MAX       (0x00000001U)

#define CSL_FEC_CTRL_FECSS_OWRITE_ERR_AGGR_RESETVAL                            (0x00000000U)

/* HW_SPARE_RW0 */

#define CSL_FEC_CTRL_HW_SPARE_RW0_HW_SPARE_RW0_HW_SPARE_RW0_MASK               (0xFFFFFFFFU)
#define CSL_FEC_CTRL_HW_SPARE_RW0_HW_SPARE_RW0_HW_SPARE_RW0_SHIFT              (0x00000000U)
#define CSL_FEC_CTRL_HW_SPARE_RW0_HW_SPARE_RW0_HW_SPARE_RW0_RESETVAL           (0x00000000U)
#define CSL_FEC_CTRL_HW_SPARE_RW0_HW_SPARE_RW0_HW_SPARE_RW0_MAX                (0xFFFFFFFFU)

#define CSL_FEC_CTRL_HW_SPARE_RW0_RESETVAL                                     (0x00000000U)

/* HW_SPARE_RW1 */

#define CSL_FEC_CTRL_HW_SPARE_RW1_HW_SPARE_RW1_HW_SPARE_RW1_MASK               (0xFFFFFFFFU)
#define CSL_FEC_CTRL_HW_SPARE_RW1_HW_SPARE_RW1_HW_SPARE_RW1_SHIFT              (0x00000000U)
#define CSL_FEC_CTRL_HW_SPARE_RW1_HW_SPARE_RW1_HW_SPARE_RW1_RESETVAL           (0x00000000U)
#define CSL_FEC_CTRL_HW_SPARE_RW1_HW_SPARE_RW1_HW_SPARE_RW1_MAX                (0xFFFFFFFFU)

#define CSL_FEC_CTRL_HW_SPARE_RW1_RESETVAL                                     (0x00000000U)

/* CM3_CPU_HALT_HANDSHAKE */

#define CSL_FEC_CTRL_CM3_CPU_HALT_HANDSHAKE_CM3_CPU_HALT_HANDSHAKE_VALUE_MASK  (0xFFFFFFFFU)
#define CSL_FEC_CTRL_CM3_CPU_HALT_HANDSHAKE_CM3_CPU_HALT_HANDSHAKE_VALUE_SHIFT (0x00000000U)
#define CSL_FEC_CTRL_CM3_CPU_HALT_HANDSHAKE_CM3_CPU_HALT_HANDSHAKE_VALUE_RESETVAL (0x00000000U)
#define CSL_FEC_CTRL_CM3_CPU_HALT_HANDSHAKE_CM3_CPU_HALT_HANDSHAKE_VALUE_MAX   (0xFFFFFFFFU)

#define CSL_FEC_CTRL_CM3_CPU_HALT_HANDSHAKE_RESETVAL                           (0x00000000U)

/* LOCK0_KICK0 */

#define CSL_FEC_CTRL_LOCK0_KICK0_LOCK0_KICK0_MASK                              (0xFFFFFFFFU)
#define CSL_FEC_CTRL_LOCK0_KICK0_LOCK0_KICK0_SHIFT                             (0x00000000U)
#define CSL_FEC_CTRL_LOCK0_KICK0_LOCK0_KICK0_RESETVAL                          (0x00000000U)
#define CSL_FEC_CTRL_LOCK0_KICK0_LOCK0_KICK0_MAX                               (0xFFFFFFFFU)

#define CSL_FEC_CTRL_LOCK0_KICK0_RESETVAL                                      (0x00000000U)

/* LOCK0_KICK1 */

#define CSL_FEC_CTRL_LOCK0_KICK1_LOCK0_KICK1_MASK                              (0xFFFFFFFFU)
#define CSL_FEC_CTRL_LOCK0_KICK1_LOCK0_KICK1_SHIFT                             (0x00000000U)
#define CSL_FEC_CTRL_LOCK0_KICK1_LOCK0_KICK1_RESETVAL                          (0x00000000U)
#define CSL_FEC_CTRL_LOCK0_KICK1_LOCK0_KICK1_MAX                               (0xFFFFFFFFU)

#define CSL_FEC_CTRL_LOCK0_KICK1_RESETVAL                                      (0x00000000U)

/* INTR_RAW_STATUS */

#define CSL_FEC_CTRL_INTR_RAW_STATUS_PROT_ERR_MASK                             (0x00000001U)
#define CSL_FEC_CTRL_INTR_RAW_STATUS_PROT_ERR_SHIFT                            (0x00000000U)
#define CSL_FEC_CTRL_INTR_RAW_STATUS_PROT_ERR_RESETVAL                         (0x00000000U)
#define CSL_FEC_CTRL_INTR_RAW_STATUS_PROT_ERR_MAX                              (0x00000001U)

#define CSL_FEC_CTRL_INTR_RAW_STATUS_ADDR_ERR_MASK                             (0x00000002U)
#define CSL_FEC_CTRL_INTR_RAW_STATUS_ADDR_ERR_SHIFT                            (0x00000001U)
#define CSL_FEC_CTRL_INTR_RAW_STATUS_ADDR_ERR_RESETVAL                         (0x00000000U)
#define CSL_FEC_CTRL_INTR_RAW_STATUS_ADDR_ERR_MAX                              (0x00000001U)

#define CSL_FEC_CTRL_INTR_RAW_STATUS_KICK_ERR_MASK                             (0x00000004U)
#define CSL_FEC_CTRL_INTR_RAW_STATUS_KICK_ERR_SHIFT                            (0x00000002U)
#define CSL_FEC_CTRL_INTR_RAW_STATUS_KICK_ERR_RESETVAL                         (0x00000000U)
#define CSL_FEC_CTRL_INTR_RAW_STATUS_KICK_ERR_MAX                              (0x00000001U)

#define CSL_FEC_CTRL_INTR_RAW_STATUS_PROXY_ERR_MASK                            (0x00000008U)
#define CSL_FEC_CTRL_INTR_RAW_STATUS_PROXY_ERR_SHIFT                           (0x00000003U)
#define CSL_FEC_CTRL_INTR_RAW_STATUS_PROXY_ERR_RESETVAL                        (0x00000000U)
#define CSL_FEC_CTRL_INTR_RAW_STATUS_PROXY_ERR_MAX                             (0x00000001U)

#define CSL_FEC_CTRL_INTR_RAW_STATUS_RESETVAL                                  (0x00000000U)

/* INTR_ENABLED_STATUS_CLEAR */

#define CSL_FEC_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROT_ERR_MASK           (0x00000001U)
#define CSL_FEC_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROT_ERR_SHIFT          (0x00000000U)
#define CSL_FEC_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROT_ERR_RESETVAL       (0x00000000U)
#define CSL_FEC_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROT_ERR_MAX            (0x00000001U)

#define CSL_FEC_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_ADDR_ERR_MASK           (0x00000002U)
#define CSL_FEC_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_ADDR_ERR_SHIFT          (0x00000001U)
#define CSL_FEC_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_ADDR_ERR_RESETVAL       (0x00000000U)
#define CSL_FEC_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_ADDR_ERR_MAX            (0x00000001U)

#define CSL_FEC_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_KICK_ERR_MASK           (0x00000004U)
#define CSL_FEC_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_KICK_ERR_SHIFT          (0x00000002U)
#define CSL_FEC_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_KICK_ERR_RESETVAL       (0x00000000U)
#define CSL_FEC_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_KICK_ERR_MAX            (0x00000001U)

#define CSL_FEC_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROXY_ERR_MASK          (0x00000008U)
#define CSL_FEC_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROXY_ERR_SHIFT         (0x00000003U)
#define CSL_FEC_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROXY_ERR_RESETVAL      (0x00000000U)
#define CSL_FEC_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROXY_ERR_MAX           (0x00000001U)

#define CSL_FEC_CTRL_INTR_ENABLED_STATUS_CLEAR_RESETVAL                        (0x00000000U)

/* INTR_ENABLE */

#define CSL_FEC_CTRL_INTR_ENABLE_PROT_ERR_EN_MASK                              (0x00000001U)
#define CSL_FEC_CTRL_INTR_ENABLE_PROT_ERR_EN_SHIFT                             (0x00000000U)
#define CSL_FEC_CTRL_INTR_ENABLE_PROT_ERR_EN_RESETVAL                          (0x00000000U)
#define CSL_FEC_CTRL_INTR_ENABLE_PROT_ERR_EN_MAX                               (0x00000001U)

#define CSL_FEC_CTRL_INTR_ENABLE_ADDR_ERR_EN_MASK                              (0x00000002U)
#define CSL_FEC_CTRL_INTR_ENABLE_ADDR_ERR_EN_SHIFT                             (0x00000001U)
#define CSL_FEC_CTRL_INTR_ENABLE_ADDR_ERR_EN_RESETVAL                          (0x00000000U)
#define CSL_FEC_CTRL_INTR_ENABLE_ADDR_ERR_EN_MAX                               (0x00000001U)

#define CSL_FEC_CTRL_INTR_ENABLE_KICK_ERR_EN_MASK                              (0x00000004U)
#define CSL_FEC_CTRL_INTR_ENABLE_KICK_ERR_EN_SHIFT                             (0x00000002U)
#define CSL_FEC_CTRL_INTR_ENABLE_KICK_ERR_EN_RESETVAL                          (0x00000000U)
#define CSL_FEC_CTRL_INTR_ENABLE_KICK_ERR_EN_MAX                               (0x00000001U)

#define CSL_FEC_CTRL_INTR_ENABLE_PROXY_ERR_EN_MASK                             (0x00000008U)
#define CSL_FEC_CTRL_INTR_ENABLE_PROXY_ERR_EN_SHIFT                            (0x00000003U)
#define CSL_FEC_CTRL_INTR_ENABLE_PROXY_ERR_EN_RESETVAL                         (0x00000000U)
#define CSL_FEC_CTRL_INTR_ENABLE_PROXY_ERR_EN_MAX                              (0x00000001U)

#define CSL_FEC_CTRL_INTR_ENABLE_RESETVAL                                      (0x00000000U)

/* INTR_ENABLE_CLEAR */

#define CSL_FEC_CTRL_INTR_ENABLE_CLEAR_PROT_ERR_EN_CLR_MASK                    (0x00000001U)
#define CSL_FEC_CTRL_INTR_ENABLE_CLEAR_PROT_ERR_EN_CLR_SHIFT                   (0x00000000U)
#define CSL_FEC_CTRL_INTR_ENABLE_CLEAR_PROT_ERR_EN_CLR_RESETVAL                (0x00000000U)
#define CSL_FEC_CTRL_INTR_ENABLE_CLEAR_PROT_ERR_EN_CLR_MAX                     (0x00000001U)

#define CSL_FEC_CTRL_INTR_ENABLE_CLEAR_ADDR_ERR_EN_CLR_MASK                    (0x00000002U)
#define CSL_FEC_CTRL_INTR_ENABLE_CLEAR_ADDR_ERR_EN_CLR_SHIFT                   (0x00000001U)
#define CSL_FEC_CTRL_INTR_ENABLE_CLEAR_ADDR_ERR_EN_CLR_RESETVAL                (0x00000000U)
#define CSL_FEC_CTRL_INTR_ENABLE_CLEAR_ADDR_ERR_EN_CLR_MAX                     (0x00000001U)

#define CSL_FEC_CTRL_INTR_ENABLE_CLEAR_KICK_ERR_EN_CLR_MASK                    (0x00000004U)
#define CSL_FEC_CTRL_INTR_ENABLE_CLEAR_KICK_ERR_EN_CLR_SHIFT                   (0x00000002U)
#define CSL_FEC_CTRL_INTR_ENABLE_CLEAR_KICK_ERR_EN_CLR_RESETVAL                (0x00000000U)
#define CSL_FEC_CTRL_INTR_ENABLE_CLEAR_KICK_ERR_EN_CLR_MAX                     (0x00000001U)

#define CSL_FEC_CTRL_INTR_ENABLE_CLEAR_PROXY_ERR_EN_CLR_MASK                   (0x00000008U)
#define CSL_FEC_CTRL_INTR_ENABLE_CLEAR_PROXY_ERR_EN_CLR_SHIFT                  (0x00000003U)
#define CSL_FEC_CTRL_INTR_ENABLE_CLEAR_PROXY_ERR_EN_CLR_RESETVAL               (0x00000000U)
#define CSL_FEC_CTRL_INTR_ENABLE_CLEAR_PROXY_ERR_EN_CLR_MAX                    (0x00000001U)

#define CSL_FEC_CTRL_INTR_ENABLE_CLEAR_RESETVAL                                (0x00000000U)

/* EOI */

#define CSL_FEC_CTRL_EOI_EOI_VECTOR_MASK                                       (0x000000FFU)
#define CSL_FEC_CTRL_EOI_EOI_VECTOR_SHIFT                                      (0x00000000U)
#define CSL_FEC_CTRL_EOI_EOI_VECTOR_RESETVAL                                   (0x00000000U)
#define CSL_FEC_CTRL_EOI_EOI_VECTOR_MAX                                        (0x000000FFU)

#define CSL_FEC_CTRL_EOI_RESETVAL                                              (0x00000000U)

/* FAULT_ADDRESS */

#define CSL_FEC_CTRL_FAULT_ADDRESS_FAULT_ADDR_MASK                             (0xFFFFFFFFU)
#define CSL_FEC_CTRL_FAULT_ADDRESS_FAULT_ADDR_SHIFT                            (0x00000000U)
#define CSL_FEC_CTRL_FAULT_ADDRESS_FAULT_ADDR_RESETVAL                         (0x00000000U)
#define CSL_FEC_CTRL_FAULT_ADDRESS_FAULT_ADDR_MAX                              (0xFFFFFFFFU)

#define CSL_FEC_CTRL_FAULT_ADDRESS_RESETVAL                                    (0x00000000U)

/* FAULT_TYPE_STATUS */

#define CSL_FEC_CTRL_FAULT_TYPE_STATUS_FAULT_TYPE_MASK                         (0x0000003FU)
#define CSL_FEC_CTRL_FAULT_TYPE_STATUS_FAULT_TYPE_SHIFT                        (0x00000000U)
#define CSL_FEC_CTRL_FAULT_TYPE_STATUS_FAULT_TYPE_RESETVAL                     (0x00000000U)
#define CSL_FEC_CTRL_FAULT_TYPE_STATUS_FAULT_TYPE_MAX                          (0x0000003FU)

#define CSL_FEC_CTRL_FAULT_TYPE_STATUS_FAULT_NS_MASK                           (0x00000040U)
#define CSL_FEC_CTRL_FAULT_TYPE_STATUS_FAULT_NS_SHIFT                          (0x00000006U)
#define CSL_FEC_CTRL_FAULT_TYPE_STATUS_FAULT_NS_RESETVAL                       (0x00000000U)
#define CSL_FEC_CTRL_FAULT_TYPE_STATUS_FAULT_NS_MAX                            (0x00000001U)

#define CSL_FEC_CTRL_FAULT_TYPE_STATUS_RESETVAL                                (0x00000000U)

/* FAULT_ATTR_STATUS */

#define CSL_FEC_CTRL_FAULT_ATTR_STATUS_FAULT_PRIVID_MASK                       (0x000000FFU)
#define CSL_FEC_CTRL_FAULT_ATTR_STATUS_FAULT_PRIVID_SHIFT                      (0x00000000U)
#define CSL_FEC_CTRL_FAULT_ATTR_STATUS_FAULT_PRIVID_RESETVAL                   (0x00000000U)
#define CSL_FEC_CTRL_FAULT_ATTR_STATUS_FAULT_PRIVID_MAX                        (0x000000FFU)

#define CSL_FEC_CTRL_FAULT_ATTR_STATUS_FAULT_ROUTEID_MASK                      (0x000FFF00U)
#define CSL_FEC_CTRL_FAULT_ATTR_STATUS_FAULT_ROUTEID_SHIFT                     (0x00000008U)
#define CSL_FEC_CTRL_FAULT_ATTR_STATUS_FAULT_ROUTEID_RESETVAL                  (0x00000000U)
#define CSL_FEC_CTRL_FAULT_ATTR_STATUS_FAULT_ROUTEID_MAX                       (0x00000FFFU)

#define CSL_FEC_CTRL_FAULT_ATTR_STATUS_FAULT_XID_MASK                          (0xFFF00000U)
#define CSL_FEC_CTRL_FAULT_ATTR_STATUS_FAULT_XID_SHIFT                         (0x00000014U)
#define CSL_FEC_CTRL_FAULT_ATTR_STATUS_FAULT_XID_RESETVAL                      (0x00000000U)
#define CSL_FEC_CTRL_FAULT_ATTR_STATUS_FAULT_XID_MAX                           (0x00000FFFU)

#define CSL_FEC_CTRL_FAULT_ATTR_STATUS_RESETVAL                                (0x00000000U)

/* FAULT_CLEAR */

#define CSL_FEC_CTRL_FAULT_CLEAR_FAULT_CLR_MASK                                (0x00000001U)
#define CSL_FEC_CTRL_FAULT_CLEAR_FAULT_CLR_SHIFT                               (0x00000000U)
#define CSL_FEC_CTRL_FAULT_CLEAR_FAULT_CLR_RESETVAL                            (0x00000000U)
#define CSL_FEC_CTRL_FAULT_CLEAR_FAULT_CLR_MAX                                 (0x00000001U)

#define CSL_FEC_CTRL_FAULT_CLEAR_RESETVAL                                      (0x00000000U)

#ifdef __cplusplus
}
#endif
#endif
