/********************************************************************
 * Copyright (C) 2021 Texas Instruments Incorporated.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *  Name        : cslr_app_hwa_adcbuf_ctrl.h
*/
#ifndef CSLR_APP_HWA_ADCBUF_CTRL_H_
#define CSLR_APP_HWA_ADCBUF_CTRL_H_

#ifdef __cplusplus
extern "C"
{
#endif
#include <drivers/hw_include/cslr.h>
#include <stdint.h>

/**************************************************************************
* Hardware Region  :
**************************************************************************/


/**************************************************************************
* Register Overlay Structure
**************************************************************************/

typedef struct {
    volatile uint32_t PID;
    volatile uint32_t HW_REG0;
    volatile uint32_t ADCBUFCFG1;
    volatile uint32_t ADCBUFCFG1_EXTD;
    volatile uint32_t ADCBUFCFG2;
    volatile uint32_t ADCBUFCFG3;
    volatile uint32_t ADCBUFCFG4;
    volatile uint32_t ADCBUFINTGENDITHERDLY;
    volatile uint32_t ADCBUFF_PING_MEM_INIT;
    volatile uint32_t ADCBUFF_PING_MEM_DONE;
    volatile uint32_t ADCBUFF_PING_MEM_STATUS;
    volatile uint32_t ADCBUFF_PONG_MEM_INIT;
    volatile uint32_t ADCBUFF_PONG_MEM_DONE;
    volatile uint32_t ADCBUFF_PONG_MEM_STATUS;
    volatile uint32_t HWASS_SHRD_RAM_MEM_INIT;
    volatile uint32_t HWASS_SHRD_RAM_MEM_DONE;
    volatile uint32_t HWASS_SHRD_RAM_MEM_STATUS;
    volatile uint32_t HWASS_SHRD_RAM_ACCESS_ERROR_MASK;
    volatile uint32_t HWASS_SHRD_RAM_ACCESS_ERROR_STATUS;
    volatile uint32_t HWASS_SHRD_RAM_ACCESS_ERROR_STATUS_RAW;
    volatile uint32_t HWASS_EDMA_CLOCK_GATE_CONTROL;
    volatile uint32_t HWASS_RAM_160KB_CLOCK_GATE;
    volatile uint8_t  Resv_4104[4016];
    volatile uint32_t LOCK0_KICK0;
    volatile uint32_t LOCK0_KICK1;
    volatile uint32_t INTR_RAW_STATUS;
    volatile uint32_t INTR_ENABLED_STATUS_CLEAR;
    volatile uint32_t INTR_ENABLE;
    volatile uint32_t INTR_ENABLE_CLEAR;
    volatile uint32_t EOI;
    volatile uint32_t FAULT_ADDRESS;
    volatile uint32_t FAULT_TYPE_STATUS;
    volatile uint32_t FAULT_ATTR_STATUS;
    volatile uint32_t FAULT_CLEAR;
} CSL_app_hwa_adcbuf_ctrlRegs;


/**************************************************************************
* Register Macros
**************************************************************************/

#define CSL_APP_HWA_ADCBUF_CTRL_PID                                            (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_HW_REG0                                        (0x00000004U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1                                     (0x00000008U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_EXTD                                (0x0000000CU)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG2                                     (0x00000010U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG3                                     (0x00000014U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG4                                     (0x00000018U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFINTGENDITHERDLY                          (0x0000001CU)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PING_MEM_INIT                          (0x00000020U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PING_MEM_DONE                          (0x00000024U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PING_MEM_STATUS                        (0x00000028U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PONG_MEM_INIT                          (0x0000002CU)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PONG_MEM_DONE                          (0x00000030U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PONG_MEM_STATUS                        (0x00000034U)
#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_MEM_INIT                        (0x00000038U)
#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_MEM_DONE                        (0x0000003CU)
#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_MEM_STATUS                      (0x00000040U)
#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_ACCESS_ERROR_MASK               (0x00000044U)
#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_ACCESS_ERROR_STATUS             (0x00000048U)
#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_ACCESS_ERROR_STATUS_RAW         (0x0000004CU)
#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_EDMA_CLOCK_GATE_CONTROL                  (0x00000050U)
#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_RAM_160KB_CLOCK_GATE                     (0x00000054U)
#define CSL_APP_HWA_ADCBUF_CTRL_LOCK0_KICK0                                    (0x00001008U)
#define CSL_APP_HWA_ADCBUF_CTRL_LOCK0_KICK1                                    (0x0000100CU)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_RAW_STATUS                                (0x00001010U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLED_STATUS_CLEAR                      (0x00001014U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE                                    (0x00001018U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_CLEAR                              (0x0000101CU)
#define CSL_APP_HWA_ADCBUF_CTRL_EOI                                            (0x00001020U)
#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_ADDRESS                                  (0x00001024U)
#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_TYPE_STATUS                              (0x00001028U)
#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_ATTR_STATUS                              (0x0000102CU)
#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_CLEAR                                    (0x00001030U)

/**************************************************************************
* Field Definition Macros
**************************************************************************/


/* PID */

#define CSL_APP_HWA_ADCBUF_CTRL_PID_PID_MINOR_MASK                             (0x0000003FU)
#define CSL_APP_HWA_ADCBUF_CTRL_PID_PID_MINOR_SHIFT                            (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_PID_PID_MINOR_RESETVAL                         (0x00000014U)
#define CSL_APP_HWA_ADCBUF_CTRL_PID_PID_MINOR_MAX                              (0x0000003FU)

#define CSL_APP_HWA_ADCBUF_CTRL_PID_PID_CUSTOM_MASK                            (0x000000C0U)
#define CSL_APP_HWA_ADCBUF_CTRL_PID_PID_CUSTOM_SHIFT                           (0x00000006U)
#define CSL_APP_HWA_ADCBUF_CTRL_PID_PID_CUSTOM_RESETVAL                        (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_PID_PID_CUSTOM_MAX                             (0x00000003U)

#define CSL_APP_HWA_ADCBUF_CTRL_PID_PID_MAJOR_MASK                             (0x00000700U)
#define CSL_APP_HWA_ADCBUF_CTRL_PID_PID_MAJOR_SHIFT                            (0x00000008U)
#define CSL_APP_HWA_ADCBUF_CTRL_PID_PID_MAJOR_RESETVAL                         (0x00000002U)
#define CSL_APP_HWA_ADCBUF_CTRL_PID_PID_MAJOR_MAX                              (0x00000007U)

#define CSL_APP_HWA_ADCBUF_CTRL_PID_PID_MISC_MASK                              (0x0000F800U)
#define CSL_APP_HWA_ADCBUF_CTRL_PID_PID_MISC_SHIFT                             (0x0000000BU)
#define CSL_APP_HWA_ADCBUF_CTRL_PID_PID_MISC_RESETVAL                          (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_PID_PID_MISC_MAX                               (0x0000001FU)

#define CSL_APP_HWA_ADCBUF_CTRL_PID_PID_MSB16_MASK                             (0xFFFF0000U)
#define CSL_APP_HWA_ADCBUF_CTRL_PID_PID_MSB16_SHIFT                            (0x00000010U)
#define CSL_APP_HWA_ADCBUF_CTRL_PID_PID_MSB16_RESETVAL                         (0x00006180U)
#define CSL_APP_HWA_ADCBUF_CTRL_PID_PID_MSB16_MAX                              (0x0000FFFFU)

#define CSL_APP_HWA_ADCBUF_CTRL_PID_RESETVAL                                   (0x61800214U)

/* HW_REG0 */

#define CSL_APP_HWA_ADCBUF_CTRL_HW_REG0_HW_REG0_HW_REG0_MASK                   (0xFFFFFFFFU)
#define CSL_APP_HWA_ADCBUF_CTRL_HW_REG0_HW_REG0_HW_REG0_SHIFT                  (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_HW_REG0_HW_REG0_HW_REG0_RESETVAL               (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_HW_REG0_HW_REG0_HW_REG0_MAX                    (0xFFFFFFFFU)

#define CSL_APP_HWA_ADCBUF_CTRL_HW_REG0_RESETVAL                               (0x00000000U)

/* ADCBUFCFG1 */

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUFWRSOURCE_MASK      (0x00000001U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUFWRSOURCE_SHIFT     (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUFWRSOURCE_RESETVAL  (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUFWRSOURCE_MAX       (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUFPIPOSELINV_MASK    (0x00000002U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUFPIPOSELINV_SHIFT   (0x00000001U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUFPIPOSELINV_RESETVAL (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUFPIPOSELINV_MAX     (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_RX0EN_MASK               (0x00000040U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_RX0EN_SHIFT              (0x00000006U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_RX0EN_RESETVAL           (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_RX0EN_MAX                (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_RX1EN_MASK               (0x00000080U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_RX1EN_SHIFT              (0x00000007U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_RX1EN_RESETVAL           (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_RX1EN_MAX                (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_RX2EN_MASK               (0x00000100U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_RX2EN_SHIFT              (0x00000008U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_RX2EN_RESETVAL           (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_RX2EN_MAX                (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_RX3EN_MASK               (0x00000200U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_RX3EN_SHIFT              (0x00000009U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_RX3EN_RESETVAL           (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_RX3EN_MAX                (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUFPIPOOVRCNT_MASK    (0x00000400U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUFPIPOOVRCNT_SHIFT   (0x0000000AU)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUFPIPOOVRCNT_RESETVAL (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUFPIPOOVRCNT_MAX     (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUFPIPOOVRVAL_MASK    (0x00000800U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUFPIPOOVRVAL_SHIFT   (0x0000000BU)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUFPIPOOVRVAL_RESETVAL (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUFPIPOOVRVAL_MAX     (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUFCONTMODEEN_MASK    (0x00002000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUFCONTMODEEN_SHIFT   (0x0000000DU)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUFCONTMODEEN_RESETVAL (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUFCONTMODEEN_MAX     (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUFCONTSTRTPL_MASK    (0x00004000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUFCONTSTRTPL_SHIFT   (0x0000000EU)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUFCONTSTRTPL_RESETVAL (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUFCONTSTRTPL_MAX     (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUFCONTSTOPPL_MASK    (0x00008000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUFCONTSTOPPL_SHIFT   (0x0000000FU)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUFCONTSTOPPL_RESETVAL (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUFCONTSTOPPL_MAX     (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUFPIPOSEL_MASK       (0x00010000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUFPIPOSEL_SHIFT      (0x00000010U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUFPIPOSEL_RESETVAL   (0x00000001U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUFPIPOSEL_MAX        (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUF_RST_MASK          (0x00020000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUF_RST_SHIFT         (0x00000011U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUF_RST_RESETVAL      (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_ADCBUFCFG1_ADCBUF_RST_MAX           (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_RESETVAL                            (0x00010000U)

/* ADCBUFCFG1_EXTD */

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_EXTD_ADCBUFCFG1_EXTD_ADCBUFINTGENDLY_MASK (0xFFFFFFFFU)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_EXTD_ADCBUFCFG1_EXTD_ADCBUFINTGENDLY_SHIFT (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_EXTD_ADCBUFCFG1_EXTD_ADCBUFINTGENDLY_RESETVAL (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_EXTD_ADCBUFCFG1_EXTD_ADCBUFINTGENDLY_MAX (0xFFFFFFFFU)

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG1_EXTD_RESETVAL                       (0x00000000U)

/* ADCBUFCFG2 */

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG2_ADCBUFCFG2_ADCBUFADDRX0_MASK        (0x000007FFU)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG2_ADCBUFCFG2_ADCBUFADDRX0_SHIFT       (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG2_ADCBUFCFG2_ADCBUFADDRX0_RESETVAL    (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG2_ADCBUFCFG2_ADCBUFADDRX0_MAX         (0x000007FFU)

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG2_ADCBUFCFG2_ADCBUFADDRX1_MASK        (0x07FF0000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG2_ADCBUFCFG2_ADCBUFADDRX1_SHIFT       (0x00000010U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG2_ADCBUFCFG2_ADCBUFADDRX1_RESETVAL    (0x00000100U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG2_ADCBUFCFG2_ADCBUFADDRX1_MAX         (0x000007FFU)

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG2_RESETVAL                            (0x01000000U)

/* ADCBUFCFG3 */

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG3_ADCBUFCFG3_ADCBUFADDRX2_MASK        (0x000007FFU)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG3_ADCBUFCFG3_ADCBUFADDRX2_SHIFT       (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG3_ADCBUFCFG3_ADCBUFADDRX2_RESETVAL    (0x00000200U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG3_ADCBUFCFG3_ADCBUFADDRX2_MAX         (0x000007FFU)

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG3_ADCBUFCFG3_ADCBUFADDRX3_MASK        (0x07FF0000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG3_ADCBUFCFG3_ADCBUFADDRX3_SHIFT       (0x00000010U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG3_ADCBUFCFG3_ADCBUFADDRX3_RESETVAL    (0x00000300U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG3_ADCBUFCFG3_ADCBUFADDRX3_MAX         (0x000007FFU)

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG3_RESETVAL                            (0x03000200U)

/* ADCBUFCFG4 */

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG4_ADCBUFCFG4_ADCBUFSAMPCNT_MASK       (0x0000FFFFU)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG4_ADCBUFCFG4_ADCBUFSAMPCNT_SHIFT      (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG4_ADCBUFCFG4_ADCBUFSAMPCNT_RESETVAL   (0x00000400U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG4_ADCBUFCFG4_ADCBUFSAMPCNT_MAX        (0x0000FFFFU)

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG4_ADCBUFCFG4_ADCBUFNUMCHRPPING_MASK   (0x001F0000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG4_ADCBUFCFG4_ADCBUFNUMCHRPPING_SHIFT  (0x00000010U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG4_ADCBUFCFG4_ADCBUFNUMCHRPPING_RESETVAL (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG4_ADCBUFCFG4_ADCBUFNUMCHRPPING_MAX    (0x0000001FU)

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG4_ADCBUFCFG4_ADCBUFPNGSELTGLDIS_MASK  (0x40000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG4_ADCBUFCFG4_ADCBUFPNGSELTGLDIS_SHIFT (0x0000001EU)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG4_ADCBUFCFG4_ADCBUFPNGSELTGLDIS_RESETVAL (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG4_ADCBUFCFG4_ADCBUFPNGSELTGLDIS_MAX   (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFCFG4_RESETVAL                            (0x00000400U)

/* ADCBUFINTGENDITHERDLY */

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFINTGENDITHERDLY_ADCBUFINTGENDITHERDLY_ADCBUFINTGENDITHERDLY_MASK (0xFFFFFFFFU)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFINTGENDITHERDLY_ADCBUFINTGENDITHERDLY_ADCBUFINTGENDITHERDLY_SHIFT (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFINTGENDITHERDLY_ADCBUFINTGENDITHERDLY_ADCBUFINTGENDITHERDLY_RESETVAL (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFINTGENDITHERDLY_ADCBUFINTGENDITHERDLY_ADCBUFINTGENDITHERDLY_MAX (0xFFFFFFFFU)

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFINTGENDITHERDLY_RESETVAL                 (0x00000000U)

/* ADCBUFF_PING_MEM_INIT */

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PING_MEM_INIT_ADCBUFF_PING_MEM_INIT_MEM_INIT_MASK (0x00000001U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PING_MEM_INIT_ADCBUFF_PING_MEM_INIT_MEM_INIT_SHIFT (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PING_MEM_INIT_ADCBUFF_PING_MEM_INIT_MEM_INIT_RESETVAL (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PING_MEM_INIT_ADCBUFF_PING_MEM_INIT_MEM_INIT_MAX (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PING_MEM_INIT_RESETVAL                 (0x00000000U)

/* ADCBUFF_PING_MEM_DONE */

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PING_MEM_DONE_ADCBUFF_PING_MEM_DONE_MEM_INIT_DONE_MASK (0x00000001U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PING_MEM_DONE_ADCBUFF_PING_MEM_DONE_MEM_INIT_DONE_SHIFT (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PING_MEM_DONE_ADCBUFF_PING_MEM_DONE_MEM_INIT_DONE_RESETVAL (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PING_MEM_DONE_ADCBUFF_PING_MEM_DONE_MEM_INIT_DONE_MAX (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PING_MEM_DONE_RESETVAL                 (0x00000000U)

/* ADCBUFF_PING_MEM_STATUS */

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PING_MEM_STATUS_ADCBUFF_PING_MEM_STATUS_MEM_INIT_STATUS_MASK (0x00000001U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PING_MEM_STATUS_ADCBUFF_PING_MEM_STATUS_MEM_INIT_STATUS_SHIFT (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PING_MEM_STATUS_ADCBUFF_PING_MEM_STATUS_MEM_INIT_STATUS_RESETVAL (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PING_MEM_STATUS_ADCBUFF_PING_MEM_STATUS_MEM_INIT_STATUS_MAX (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PING_MEM_STATUS_RESETVAL               (0x00000000U)

/* ADCBUFF_PONG_MEM_INIT */

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PONG_MEM_INIT_ADCBUFF_PONG_MEM_INIT_MEM_INIT_MASK (0x00000001U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PONG_MEM_INIT_ADCBUFF_PONG_MEM_INIT_MEM_INIT_SHIFT (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PONG_MEM_INIT_ADCBUFF_PONG_MEM_INIT_MEM_INIT_RESETVAL (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PONG_MEM_INIT_ADCBUFF_PONG_MEM_INIT_MEM_INIT_MAX (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PONG_MEM_INIT_RESETVAL                 (0x00000000U)

/* ADCBUFF_PONG_MEM_DONE */

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PONG_MEM_DONE_ADCBUFF_PONG_MEM_DONE_MEM_INIT_DONE_MASK (0x00000001U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PONG_MEM_DONE_ADCBUFF_PONG_MEM_DONE_MEM_INIT_DONE_SHIFT (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PONG_MEM_DONE_ADCBUFF_PONG_MEM_DONE_MEM_INIT_DONE_RESETVAL (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PONG_MEM_DONE_ADCBUFF_PONG_MEM_DONE_MEM_INIT_DONE_MAX (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PONG_MEM_DONE_RESETVAL                 (0x00000000U)

/* ADCBUFF_PONG_MEM_STATUS */

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PONG_MEM_STATUS_ADCBUFF_PONG_MEM_STATUS_MEM_INIT_STATUS_MASK (0x00000001U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PONG_MEM_STATUS_ADCBUFF_PONG_MEM_STATUS_MEM_INIT_STATUS_SHIFT (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PONG_MEM_STATUS_ADCBUFF_PONG_MEM_STATUS_MEM_INIT_STATUS_RESETVAL (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PONG_MEM_STATUS_ADCBUFF_PONG_MEM_STATUS_MEM_INIT_STATUS_MAX (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_ADCBUFF_PONG_MEM_STATUS_RESETVAL               (0x00000000U)

/* HWASS_SHRD_RAM_MEM_INIT */

#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_MEM_INIT_HWASS_SHRD_RAM_MEM_INIT_MEM_INIT_MASK (0x00000001U)
#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_MEM_INIT_HWASS_SHRD_RAM_MEM_INIT_MEM_INIT_SHIFT (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_MEM_INIT_HWASS_SHRD_RAM_MEM_INIT_MEM_INIT_RESETVAL (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_MEM_INIT_HWASS_SHRD_RAM_MEM_INIT_MEM_INIT_MAX (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_MEM_INIT_RESETVAL               (0x00000000U)

/* HWASS_SHRD_RAM_MEM_DONE */

#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_MEM_DONE_HWASS_SHRD_RAM_MEM_DONE_MEM_INIT_DONE_MASK (0x00000001U)
#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_MEM_DONE_HWASS_SHRD_RAM_MEM_DONE_MEM_INIT_DONE_SHIFT (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_MEM_DONE_HWASS_SHRD_RAM_MEM_DONE_MEM_INIT_DONE_RESETVAL (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_MEM_DONE_HWASS_SHRD_RAM_MEM_DONE_MEM_INIT_DONE_MAX (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_MEM_DONE_RESETVAL               (0x00000000U)

/* HWASS_SHRD_RAM_MEM_STATUS */

#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_MEM_STATUS_HWASS_SHRD_RAM_MEM_STATUS_MEM_INIT_STATUS_MASK (0x00000001U)
#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_MEM_STATUS_HWASS_SHRD_RAM_MEM_STATUS_MEM_INIT_STATUS_SHIFT (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_MEM_STATUS_HWASS_SHRD_RAM_MEM_STATUS_MEM_INIT_STATUS_RESETVAL (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_MEM_STATUS_HWASS_SHRD_RAM_MEM_STATUS_MEM_INIT_STATUS_MAX (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_MEM_STATUS_RESETVAL             (0x00000000U)

/* HWASS_SHRD_RAM_ACCESS_ERROR_MASK */

#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_ACCESS_ERROR_MASK_HWASS_SHRD_RAM_ACCESS_ERROR_MASK_SHMEM_ACCESS_ERROR_MASK_MASK (0x00000001U)
#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_ACCESS_ERROR_MASK_HWASS_SHRD_RAM_ACCESS_ERROR_MASK_SHMEM_ACCESS_ERROR_MASK_SHIFT (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_ACCESS_ERROR_MASK_HWASS_SHRD_RAM_ACCESS_ERROR_MASK_SHMEM_ACCESS_ERROR_MASK_RESETVAL (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_ACCESS_ERROR_MASK_HWASS_SHRD_RAM_ACCESS_ERROR_MASK_SHMEM_ACCESS_ERROR_MASK_MAX (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_ACCESS_ERROR_MASK_RESETVAL      (0x00000000U)

/* HWASS_SHRD_RAM_ACCESS_ERROR_STATUS */

#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_ACCESS_ERROR_STATUS_HWASS_SHRD_RAM_ACCESS_ERROR_STATUS_SHMEM_ACCESS_ERROR_STATUS_MASK (0x00000001U)
#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_ACCESS_ERROR_STATUS_HWASS_SHRD_RAM_ACCESS_ERROR_STATUS_SHMEM_ACCESS_ERROR_STATUS_SHIFT (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_ACCESS_ERROR_STATUS_HWASS_SHRD_RAM_ACCESS_ERROR_STATUS_SHMEM_ACCESS_ERROR_STATUS_RESETVAL (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_ACCESS_ERROR_STATUS_HWASS_SHRD_RAM_ACCESS_ERROR_STATUS_SHMEM_ACCESS_ERROR_STATUS_MAX (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_ACCESS_ERROR_STATUS_RESETVAL    (0x00000000U)

/* HWASS_SHRD_RAM_ACCESS_ERROR_STATUS_RAW */

#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_ACCESS_ERROR_STATUS_RAW_HWASS_SHRD_RAM_ACCESS_ERROR_STATUS_RAW_SHMEM_ACCESS_ERRROR_STATUS_RAW_MASK (0x00000001U)
#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_ACCESS_ERROR_STATUS_RAW_HWASS_SHRD_RAM_ACCESS_ERROR_STATUS_RAW_SHMEM_ACCESS_ERRROR_STATUS_RAW_SHIFT (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_ACCESS_ERROR_STATUS_RAW_HWASS_SHRD_RAM_ACCESS_ERROR_STATUS_RAW_SHMEM_ACCESS_ERRROR_STATUS_RAW_RESETVAL (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_ACCESS_ERROR_STATUS_RAW_HWASS_SHRD_RAM_ACCESS_ERROR_STATUS_RAW_SHMEM_ACCESS_ERRROR_STATUS_RAW_MAX (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_SHRD_RAM_ACCESS_ERROR_STATUS_RAW_RESETVAL (0x00000000U)

/* HWASS_EDMA_CLOCK_GATE_CONTROL */

#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_EDMA_CLOCK_GATE_CONTROL_HWASS_EDMA_CLOCK_GATE_CONTROL_HWA_EDMA_CLOCK_GATING_EN_MASK (0x00000007U)
#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_EDMA_CLOCK_GATE_CONTROL_HWASS_EDMA_CLOCK_GATE_CONTROL_HWA_EDMA_CLOCK_GATING_EN_SHIFT (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_EDMA_CLOCK_GATE_CONTROL_HWASS_EDMA_CLOCK_GATE_CONTROL_HWA_EDMA_CLOCK_GATING_EN_RESETVAL (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_EDMA_CLOCK_GATE_CONTROL_HWASS_EDMA_CLOCK_GATE_CONTROL_HWA_EDMA_CLOCK_GATING_EN_MAX (0x00000007U)

#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_EDMA_CLOCK_GATE_CONTROL_RESETVAL         (0x00000000U)

/* HWASS_RAM_160KB_CLOCK_GATE */

#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_RAM_160KB_CLOCK_GATE_HWASS_RAM_160KB_CLOCK_GATE_ENABLE_MASK (0x00000007U)
#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_RAM_160KB_CLOCK_GATE_HWASS_RAM_160KB_CLOCK_GATE_ENABLE_SHIFT (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_RAM_160KB_CLOCK_GATE_HWASS_RAM_160KB_CLOCK_GATE_ENABLE_RESETVAL (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_RAM_160KB_CLOCK_GATE_HWASS_RAM_160KB_CLOCK_GATE_ENABLE_MAX (0x00000007U)

#define CSL_APP_HWA_ADCBUF_CTRL_HWASS_RAM_160KB_CLOCK_GATE_RESETVAL            (0x00000000U)

/* LOCK0_KICK0 */

#define CSL_APP_HWA_ADCBUF_CTRL_LOCK0_KICK0_LOCK0_KICK0_MASK                   (0xFFFFFFFFU)
#define CSL_APP_HWA_ADCBUF_CTRL_LOCK0_KICK0_LOCK0_KICK0_SHIFT                  (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_LOCK0_KICK0_LOCK0_KICK0_RESETVAL               (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_LOCK0_KICK0_LOCK0_KICK0_MAX                    (0xFFFFFFFFU)

#define CSL_APP_HWA_ADCBUF_CTRL_LOCK0_KICK0_RESETVAL                           (0x00000000U)

/* LOCK0_KICK1 */

#define CSL_APP_HWA_ADCBUF_CTRL_LOCK0_KICK1_LOCK0_KICK1_MASK                   (0xFFFFFFFFU)
#define CSL_APP_HWA_ADCBUF_CTRL_LOCK0_KICK1_LOCK0_KICK1_SHIFT                  (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_LOCK0_KICK1_LOCK0_KICK1_RESETVAL               (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_LOCK0_KICK1_LOCK0_KICK1_MAX                    (0xFFFFFFFFU)

#define CSL_APP_HWA_ADCBUF_CTRL_LOCK0_KICK1_RESETVAL                           (0x00000000U)

/* INTR_RAW_STATUS */

#define CSL_APP_HWA_ADCBUF_CTRL_INTR_RAW_STATUS_PROT_ERR_MASK                  (0x00000001U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_RAW_STATUS_PROT_ERR_SHIFT                 (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_RAW_STATUS_PROT_ERR_RESETVAL              (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_RAW_STATUS_PROT_ERR_MAX                   (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_INTR_RAW_STATUS_ADDR_ERR_MASK                  (0x00000002U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_RAW_STATUS_ADDR_ERR_SHIFT                 (0x00000001U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_RAW_STATUS_ADDR_ERR_RESETVAL              (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_RAW_STATUS_ADDR_ERR_MAX                   (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_INTR_RAW_STATUS_KICK_ERR_MASK                  (0x00000004U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_RAW_STATUS_KICK_ERR_SHIFT                 (0x00000002U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_RAW_STATUS_KICK_ERR_RESETVAL              (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_RAW_STATUS_KICK_ERR_MAX                   (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_INTR_RAW_STATUS_PROXY_ERR_MASK                 (0x00000008U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_RAW_STATUS_PROXY_ERR_SHIFT                (0x00000003U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_RAW_STATUS_PROXY_ERR_RESETVAL             (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_RAW_STATUS_PROXY_ERR_MAX                  (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_INTR_RAW_STATUS_RESETVAL                       (0x00000000U)

/* INTR_ENABLED_STATUS_CLEAR */

#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROT_ERR_MASK (0x00000001U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROT_ERR_SHIFT (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROT_ERR_RESETVAL (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROT_ERR_MAX (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_ADDR_ERR_MASK (0x00000002U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_ADDR_ERR_SHIFT (0x00000001U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_ADDR_ERR_RESETVAL (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_ADDR_ERR_MAX (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_KICK_ERR_MASK (0x00000004U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_KICK_ERR_SHIFT (0x00000002U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_KICK_ERR_RESETVAL (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_KICK_ERR_MAX (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROXY_ERR_MASK (0x00000008U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROXY_ERR_SHIFT (0x00000003U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROXY_ERR_RESETVAL (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROXY_ERR_MAX (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLED_STATUS_CLEAR_RESETVAL             (0x00000000U)

/* INTR_ENABLE */

#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_PROT_ERR_EN_MASK                   (0x00000001U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_PROT_ERR_EN_SHIFT                  (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_PROT_ERR_EN_RESETVAL               (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_PROT_ERR_EN_MAX                    (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_ADDR_ERR_EN_MASK                   (0x00000002U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_ADDR_ERR_EN_SHIFT                  (0x00000001U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_ADDR_ERR_EN_RESETVAL               (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_ADDR_ERR_EN_MAX                    (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_KICK_ERR_EN_MASK                   (0x00000004U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_KICK_ERR_EN_SHIFT                  (0x00000002U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_KICK_ERR_EN_RESETVAL               (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_KICK_ERR_EN_MAX                    (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_PROXY_ERR_EN_MASK                  (0x00000008U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_PROXY_ERR_EN_SHIFT                 (0x00000003U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_PROXY_ERR_EN_RESETVAL              (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_PROXY_ERR_EN_MAX                   (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_RESETVAL                           (0x00000000U)

/* INTR_ENABLE_CLEAR */

#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_CLEAR_PROT_ERR_EN_CLR_MASK         (0x00000001U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_CLEAR_PROT_ERR_EN_CLR_SHIFT        (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_CLEAR_PROT_ERR_EN_CLR_RESETVAL     (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_CLEAR_PROT_ERR_EN_CLR_MAX          (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_CLEAR_ADDR_ERR_EN_CLR_MASK         (0x00000002U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_CLEAR_ADDR_ERR_EN_CLR_SHIFT        (0x00000001U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_CLEAR_ADDR_ERR_EN_CLR_RESETVAL     (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_CLEAR_ADDR_ERR_EN_CLR_MAX          (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_CLEAR_KICK_ERR_EN_CLR_MASK         (0x00000004U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_CLEAR_KICK_ERR_EN_CLR_SHIFT        (0x00000002U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_CLEAR_KICK_ERR_EN_CLR_RESETVAL     (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_CLEAR_KICK_ERR_EN_CLR_MAX          (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_CLEAR_PROXY_ERR_EN_CLR_MASK        (0x00000008U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_CLEAR_PROXY_ERR_EN_CLR_SHIFT       (0x00000003U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_CLEAR_PROXY_ERR_EN_CLR_RESETVAL    (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_CLEAR_PROXY_ERR_EN_CLR_MAX         (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_INTR_ENABLE_CLEAR_RESETVAL                     (0x00000000U)

/* EOI */

#define CSL_APP_HWA_ADCBUF_CTRL_EOI_EOI_VECTOR_MASK                            (0x000000FFU)
#define CSL_APP_HWA_ADCBUF_CTRL_EOI_EOI_VECTOR_SHIFT                           (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_EOI_EOI_VECTOR_RESETVAL                        (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_EOI_EOI_VECTOR_MAX                             (0x000000FFU)

#define CSL_APP_HWA_ADCBUF_CTRL_EOI_RESETVAL                                   (0x00000000U)

/* FAULT_ADDRESS */

#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_ADDRESS_FAULT_ADDR_MASK                  (0xFFFFFFFFU)
#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_ADDRESS_FAULT_ADDR_SHIFT                 (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_ADDRESS_FAULT_ADDR_RESETVAL              (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_ADDRESS_FAULT_ADDR_MAX                   (0xFFFFFFFFU)

#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_ADDRESS_RESETVAL                         (0x00000000U)

/* FAULT_TYPE_STATUS */

#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_TYPE_STATUS_FAULT_TYPE_MASK              (0x0000003FU)
#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_TYPE_STATUS_FAULT_TYPE_SHIFT             (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_TYPE_STATUS_FAULT_TYPE_RESETVAL          (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_TYPE_STATUS_FAULT_TYPE_MAX               (0x0000003FU)

#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_TYPE_STATUS_FAULT_NS_MASK                (0x00000040U)
#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_TYPE_STATUS_FAULT_NS_SHIFT               (0x00000006U)
#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_TYPE_STATUS_FAULT_NS_RESETVAL            (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_TYPE_STATUS_FAULT_NS_MAX                 (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_TYPE_STATUS_RESETVAL                     (0x00000000U)

/* FAULT_ATTR_STATUS */

#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_ATTR_STATUS_FAULT_PRIVID_MASK            (0x000000FFU)
#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_ATTR_STATUS_FAULT_PRIVID_SHIFT           (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_ATTR_STATUS_FAULT_PRIVID_RESETVAL        (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_ATTR_STATUS_FAULT_PRIVID_MAX             (0x000000FFU)

#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_ATTR_STATUS_FAULT_ROUTEID_MASK           (0x000FFF00U)
#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_ATTR_STATUS_FAULT_ROUTEID_SHIFT          (0x00000008U)
#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_ATTR_STATUS_FAULT_ROUTEID_RESETVAL       (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_ATTR_STATUS_FAULT_ROUTEID_MAX            (0x00000FFFU)

#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_ATTR_STATUS_FAULT_XID_MASK               (0xFFF00000U)
#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_ATTR_STATUS_FAULT_XID_SHIFT              (0x00000014U)
#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_ATTR_STATUS_FAULT_XID_RESETVAL           (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_ATTR_STATUS_FAULT_XID_MAX                (0x00000FFFU)

#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_ATTR_STATUS_RESETVAL                     (0x00000000U)

/* FAULT_CLEAR */

#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_CLEAR_FAULT_CLR_MASK                     (0x00000001U)
#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_CLEAR_FAULT_CLR_SHIFT                    (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_CLEAR_FAULT_CLR_RESETVAL                 (0x00000000U)
#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_CLEAR_FAULT_CLR_MAX                      (0x00000001U)

#define CSL_APP_HWA_ADCBUF_CTRL_FAULT_CLEAR_RESETVAL                           (0x00000000U)

#ifdef __cplusplus
}
#endif
#endif
